'use client';

import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import Chip from '@mui/material/Chip';
import Stack from '@mui/material/Stack';
import Divider from '@mui/material/Divider';
import Tooltip from '@mui/material/Tooltip';
import Typography from '@mui/material/Typography';

import { fCurrency } from 'src/utils/format-number';

import { Iconify } from 'src/components/iconify';

// ----------------------------------------------------------------------

function renderLeaveBreakdown(breakdown) {
  if (!breakdown || typeof breakdown !== 'object' || Object.keys(breakdown).length === 0) {
    return null;
  }
  return Object.entries(breakdown);
}

// ----------------------------------------------------------------------

export function PayrollInvoiceDetails({ payroll, companyInfo }) {
  if (!payroll) return null;

  const employeeName = payroll.employee?.split(' - ')?.[0] || payroll.employee || 'N/A';
  const employeeId = payroll.employee?.split(' - ')?.[1] || '';

  const totalDeductions =
    parseFloat(payroll.absence_deduction || 0) +
    parseFloat(payroll.late_deduction || 0) +
    parseFloat(payroll.tax_deduction || 0);

  const totalBonuses =
    parseFloat(payroll.festival_bonus || 0) + parseFloat(payroll.performance_bonus || 0);
  const totalCompensations =
    parseFloat(payroll.holiday_compensation || 0) + parseFloat(payroll.weekday_compensation || 0);

  const attendanceRate =
    payroll.working_days > 0
      ? ((payroll.present_days / payroll.working_days) * 100).toFixed(1)
      : '0.0';

  const leaveEntries = renderLeaveBreakdown(payroll.leave_breakdown);

  return (
    <Card sx={{ pt: 5, px: 5, pb: 3 }}>
      {/* Header with Logo */}
      <Box display="flex" alignItems="center" justifyContent="center" mb={2}>
        {companyInfo?.logo ? (
          <Box
            component="img"
            alt={companyInfo.company_name || 'Company Logo'}
            src={companyInfo.logo}
            sx={{ maxWidth: 200, maxHeight: 80, objectFit: 'contain' }}
          />
        ) : (
          <Typography variant="h4" color="primary.main" fontWeight="bold">
            {companyInfo?.company_name || 'Company'}
          </Typography>
        )}
      </Box>

      {companyInfo?.company_name && (
        <Typography variant="h6" textAlign="center" color="text.secondary" mb={1}>
          {companyInfo.company_name}
        </Typography>
      )}

      <Typography
        variant="h6"
        textAlign="center"
        textTransform="uppercase"
        sx={{ textDecoration: 'underline', mb: 3 }}
      >
        Payslip for {payroll.payroll_month} {payroll.payroll_year}
      </Typography>

      {/* Employee & Payroll Info Header */}
      <Box gap={3} display="grid" gridTemplateColumns={{ xs: '1fr', sm: '1fr 1fr' }} sx={{ mb: 4 }}>
        <Stack spacing={1}>
          <Stack direction="row" spacing={1} alignItems="center">
            <Iconify icon="solar:user-bold-duotone" width={20} sx={{ color: 'primary.main' }} />
            <Typography variant="subtitle1">{employeeName}</Typography>
            {payroll.is_locked && (
              <Tooltip title="This payroll is locked">
                <Iconify icon="solar:lock-bold" width={18} sx={{ color: 'warning.main' }} />
              </Tooltip>
            )}
          </Stack>
          {employeeId && (
            <Typography variant="body2" color="text.secondary" sx={{ pl: 3.5 }}>
              ID: {employeeId}
            </Typography>
          )}
          <Typography variant="body2" color="text.secondary" sx={{ pl: 3.5 }}>
            Generated by: {payroll.creator}
          </Typography>
        </Stack>

        <Stack alignItems={{ xs: 'flex-start', sm: 'flex-end' }} spacing={1}>
          <Stack direction="row" spacing={1} alignItems="center">
            <Chip
              label={`Payslip #${payroll.id}`}
              color="primary"
              variant="filled"
              size="small"
              icon={<Iconify icon="solar:document-text-bold" />}
            />
            {payroll.is_locked && (
              <Chip
                label="Locked"
                color="warning"
                variant="soft"
                size="small"
                icon={<Iconify icon="solar:lock-bold" />}
              />
            )}
          </Stack>
          <Typography variant="body2" color="text.secondary">
            Created:{' '}
            {payroll.created_at ? new Date(payroll.created_at).toLocaleDateString() : 'N/A'}
          </Typography>
          {payroll.updated_at !== payroll.created_at && (
            <Typography variant="caption" color="text.disabled">
              Updated: {new Date(payroll.updated_at).toLocaleDateString()}
            </Typography>
          )}
        </Stack>
      </Box>

      <Divider sx={{ mb: 3 }} />

      {/* Main Content: Earnings & Deductions side by side */}
      <Box gap={4} display="grid" gridTemplateColumns={{ xs: '1fr', sm: '1fr 1fr' }}>
        {/* LEFT: Earnings */}
        <Box>
          <Stack direction="row" spacing={1} alignItems="center" sx={{ mb: 2 }}>
            <Box
              sx={{
                width: 32,
                height: 32,
                display: 'flex',
                borderRadius: 1,
                alignItems: 'center',
                justifyContent: 'center',
                bgcolor: 'success.lighter',
                color: 'success.main',
              }}
            >
              <Iconify icon="solar:wallet-money-bold-duotone" width={20} />
            </Box>
            <Typography variant="h6">Earnings</Typography>
          </Stack>

          <Stack spacing={0} divider={<Divider sx={{ borderStyle: 'dashed' }} />}>
            <LineItem label="Basic Salary" value={fCurrency(payroll.basic)} />
            <LineItem label="House Rent Allowance" value={fCurrency(payroll.house_rent)} />
            <LineItem label="Conveyance Allowance" value={fCurrency(payroll.conveyance)} />
            <LineItem label="Medical Allowance" value={fCurrency(payroll.medical)} />
            <LineItem label="Gross Salary" value={fCurrency(payroll.gross_salary)} bold highlight />

            <Box sx={{ pt: 1 }} />

            <LineItem label="Festival Bonus" value={fCurrency(payroll.festival_bonus)} />
            <LineItem label="Performance Bonus" value={fCurrency(payroll.performance_bonus)} />
            <LineItem
              label="Holiday Compensation"
              value={fCurrency(payroll.holiday_compensation)}
            />
            <LineItem
              label="Weekday Compensation"
              value={fCurrency(payroll.weekday_compensation)}
            />

            <LineItem
              label="Total Bonuses & Compensation"
              value={fCurrency(totalBonuses + totalCompensations)}
              bold
              highlight
            />
          </Stack>
        </Box>

        {/* RIGHT: Deductions + Attendance */}
        <Box>
          <Stack direction="row" spacing={1} alignItems="center" sx={{ mb: 2 }}>
            <Box
              sx={{
                width: 32,
                height: 32,
                display: 'flex',
                borderRadius: 1,
                alignItems: 'center',
                justifyContent: 'center',
                bgcolor: 'error.lighter',
                color: 'error.main',
              }}
            >
              <Iconify icon="solar:minus-circle-bold-duotone" width={20} />
            </Box>
            <Typography variant="h6">Deductions</Typography>
          </Stack>

          <Stack spacing={0} divider={<Divider sx={{ borderStyle: 'dashed' }} />}>
            <LineItem
              label="Absence Deduction"
              value={fCurrency(payroll.absence_deduction)}
              negative
            />
            <LineItem label="Late Deduction" value={fCurrency(payroll.late_deduction)} negative />
            <LineItem label="Tax Deduction" value={fCurrency(payroll.tax_deduction)} negative />
            <LineItem
              label="Total Deductions"
              value={fCurrency(totalDeductions)}
              bold
              negative
              highlight
            />
          </Stack>

          {/* Attendance Card */}
          <Stack direction="row" spacing={1} alignItems="center" sx={{ mt: 3, mb: 2 }}>
            <Box
              sx={{
                width: 32,
                height: 32,
                display: 'flex',
                borderRadius: 1,
                alignItems: 'center',
                justifyContent: 'center',
                bgcolor: 'info.lighter',
                color: 'info.main',
              }}
            >
              <Iconify icon="solar:calendar-bold-duotone" width={20} />
            </Box>
            <Typography variant="h6">Attendance</Typography>
          </Stack>

          <Stack spacing={0} divider={<Divider sx={{ borderStyle: 'dashed' }} />}>
            <LineItem label="Days in Month" value={payroll.days_of_month} />
            <LineItem label="Working Days" value={payroll.working_days} />
            <LineItem label="Present Days" value={payroll.present_days} />
            <LineItem label="Absent Days" value={payroll.absent_days} />
            <LineItem label="Late Days" value={payroll.late_days || 0} />
            <LineItem label="Weekend Days" value={payroll.weekend_days} />
            <LineItem label="Holidays" value={payroll.holidays} />
            <LineItem label="Attendance Rate" value={`${attendanceRate}%`} bold highlight />
          </Stack>

          {/* Leave Breakdown */}
          {leaveEntries && leaveEntries.length > 0 && (
            <Box sx={{ mt: 1.5, p: 1.5, borderRadius: 1, bgcolor: 'background.neutral' }}>
              <Typography
                variant="caption"
                color="text.disabled"
                sx={{ mb: 0.5, display: 'block' }}
              >
                Leave Breakdown
              </Typography>
              <Stack spacing={0.5}>
                {leaveEntries.map(([type, days]) => (
                  <Stack key={type} direction="row" justifyContent="space-between">
                    <Typography variant="body2" color="text.secondary">
                      {type}
                    </Typography>
                    <Typography variant="body2" fontWeight="medium">
                      {days} day(s)
                    </Typography>
                  </Stack>
                ))}
              </Stack>
            </Box>
          )}
        </Box>
      </Box>

      <Divider sx={{ mt: 3 }} />

      {/* Net Salary & Transfer Summary */}
      <Box sx={{ py: 3 }}>
        <Typography variant="h5" textAlign="center" color="primary.main">
          Net Salary: {fCurrency(payroll.net_salary)}
        </Typography>
        <Typography variant="body2" textAlign="center" color="text.secondary" sx={{ mt: 0.5 }}>
          (Gross {fCurrency(payroll.gross_salary)} + Bonuses{' '}
          {fCurrency(totalBonuses + totalCompensations)} − Deductions {fCurrency(totalDeductions)})
        </Typography>
        {parseFloat(payroll.total_transfer_amount || 0) > 0 && (
          <Typography variant="h6" textAlign="center" color="success.main" sx={{ mt: 1 }}>
            Total Transfer Amount: {fCurrency(payroll.total_transfer_amount)}
          </Typography>
        )}
      </Box>

      <Divider sx={{ borderStyle: 'dashed' }} />

      {/* Signatures */}
      <Box
        gap={5}
        py={3}
        display="grid"
        alignItems="center"
        gridTemplateColumns={{ xs: '1fr', sm: '1fr 1fr' }}
      >
        <Box display="flex" flexDirection="column" alignItems="center">
          <Typography variant="subtitle1" sx={{ mb: 10 }} textAlign="center">
            Employer Signature
          </Typography>
          <Divider sx={{ width: '60%', borderColor: 'grey.900' }} />
        </Box>

        <Box display="flex" flexDirection="column" alignItems="center">
          <Typography variant="subtitle1" sx={{ mb: 10 }} textAlign="center">
            Employee Signature
          </Typography>
          <Divider sx={{ width: '60%', borderColor: 'grey.900' }} />
        </Box>
      </Box>

      <Typography variant="body2" py={2} textAlign="center" color="text.disabled">
        This is a system-generated payslip
      </Typography>
    </Card>
  );
}

// ----------------------------------------------------------------------

function LineItem({ label, value, bold, negative, highlight }) {
  return (
    <Stack
      direction="row"
      justifyContent="space-between"
      alignItems="center"
      sx={{
        py: 0.75,
        px: 1,
        ...(highlight && { bgcolor: 'background.neutral', borderRadius: 0.5 }),
      }}
    >
      <Typography
        variant={bold ? 'subtitle2' : 'body2'}
        color={negative ? 'error.main' : 'text.primary'}
      >
        {label}
      </Typography>
      <Typography
        variant={bold ? 'subtitle2' : 'body2'}
        fontWeight={bold ? 'bold' : 'normal'}
        color={
          // eslint-disable-next-line no-nested-ternary
          negative ? 'error.main' : bold ? 'text.primary' : 'text.secondary'
        }
      >
        {negative && parseFloat(String(value).replace(/[^0-9.-]/g, '')) > 0 ? '- ' : ''}
        {value}
      </Typography>
    </Stack>
  );
}
