const ROOTS = {
  AUTH: '/auth',
  DASHBOARD: '/dashboard',
};

// ----------------------------------------------------------------------

export const paths = {
  page403: '/error/403',
  page404: '/error/404',
  page500: '/error/500',
  docs: 'https://docs.minimals.cc',
  changelog: 'https://docs.minimals.cc/changelog',
  zoneStore: 'https://mui.com/store/items/zone-landing-page/',
  minimalStore: 'https://mui.com/store/items/minimal-dashboard/',
  freeUI: 'https://mui.com/store/items/minimal-dashboard-free/',
  figmaUrl: 'https://www.figma.com/design/cAPz4pYPtQEXivqe11EcDE/%5BPreview%5D-Minimal-Web.v6.0.0',
  resetPasswordConfirm: '/password/reset/confirm',
  // AUTH
  auth: {
    jwt: {
      signIn: `${ROOTS.AUTH}/jwt/sign-in`,
      resetPassword: `${ROOTS.AUTH}/jwt/reset-password`,
    },
  },
  // DASHBOARD
  dashboard: {
    root: ROOTS.DASHBOARD,
    mail: `${ROOTS.DASHBOARD}/mail`,
    permission: `${ROOTS.DASHBOARD}/permission`,
    blank: `${ROOTS.DASHBOARD}/blank`,
    general: {
      app: `${ROOTS.DASHBOARD}/app`,
    },
    hrm: `${ROOTS.DASHBOARD}/hrm`,
    beneficiaries: {
      root: `${ROOTS.DASHBOARD}/beneficiaries`,
      // Dashboard
      dashboard: `${ROOTS.DASHBOARD}/beneficiaries/dashboard`,
      // Registration & Database
      database: `${ROOTS.DASHBOARD}/beneficiaries/database`,
      add_database: `${ROOTS.DASHBOARD}/beneficiaries/database/add-database`,
      bulk_registration: `${ROOTS.DASHBOARD}/beneficiaries/bulk-registration`,
      duplicate_management: `${ROOTS.DASHBOARD}/beneficiaries/duplicate-management`,
      id_card_generation: `${ROOTS.DASHBOARD}/beneficiaries/id-card-generation`,
      beneficiary_import: `${ROOTS.DASHBOARD}/beneficiaries/import`,
      // Service Delivery
      service_delivery: `${ROOTS.DASHBOARD}/beneficiaries/service-delivery`,
      service_categories: `${ROOTS.DASHBOARD}/beneficiaries/service-categories`,
      service_calendar: `${ROOTS.DASHBOARD}/beneficiaries/service-calendar`,
      distribution_plan: `${ROOTS.DASHBOARD}/beneficiaries/distribution-plan`,
      // Case Management
      case_management: `${ROOTS.DASHBOARD}/beneficiaries/case-management`,
      case_worker_assignment: `${ROOTS.DASHBOARD}/beneficiaries/case-worker-assignment`,
      follow_up_schedule: `${ROOTS.DASHBOARD}/beneficiaries/follow-up-schedule`,
      // Assessment & Targeting
      vulnerability_assessment: `${ROOTS.DASHBOARD}/beneficiaries/vulnerability-assessment`,
      targeting_criteria: `${ROOTS.DASHBOARD}/beneficiaries/targeting-criteria`,
      needs_assessment: `${ROOTS.DASHBOARD}/beneficiaries/needs-assessment`,
      eligibility_screening: `${ROOTS.DASHBOARD}/beneficiaries/eligibility-screening`,
      // Household Management
      household_profiling: `${ROOTS.DASHBOARD}/beneficiaries/household-profiling`,
      household_surveys: `${ROOTS.DASHBOARD}/beneficiaries/household-surveys`,
      // Monitoring & Impact
      impact_measurement: `${ROOTS.DASHBOARD}/beneficiaries/impact-measurement`,
      outcome_indicators: `${ROOTS.DASHBOARD}/beneficiaries/outcome-indicators`,
      progress_tracking: `${ROOTS.DASHBOARD}/beneficiaries/progress-tracking`,
      // Referral & Linkages
      referral_management: `${ROOTS.DASHBOARD}/beneficiaries/referral-management`,
      referral_network: `${ROOTS.DASHBOARD}/beneficiaries/referral-network`,
      // Accountability
      complaints_feedback: `${ROOTS.DASHBOARD}/beneficiaries/complaints-feedback`,
      satisfaction_surveys: `${ROOTS.DASHBOARD}/beneficiaries/satisfaction-surveys`,
      grievance_redressal: `${ROOTS.DASHBOARD}/beneficiaries/grievance-redressal`,
      // Exit & Graduation
      exit_graduation: `${ROOTS.DASHBOARD}/beneficiaries/exit-graduation`,
      graduation_criteria: `${ROOTS.DASHBOARD}/beneficiaries/graduation-criteria`,
      alumni_tracking: `${ROOTS.DASHBOARD}/beneficiaries/alumni-tracking`,
      // Protection & Safeguarding
      protection_cases: `${ROOTS.DASHBOARD}/beneficiaries/protection-cases`,
      consent_management: `${ROOTS.DASHBOARD}/beneficiaries/consent-management`,
      safeguarding_incidents: `${ROOTS.DASHBOARD}/beneficiaries/safeguarding-incidents`,
      // Reports & Analytics
      beneficiary_analytics: `${ROOTS.DASHBOARD}/beneficiaries/beneficiary-analytics`,
      demographic_report: `${ROOTS.DASHBOARD}/beneficiaries/demographic-report`,
      coverage_map: `${ROOTS.DASHBOARD}/beneficiaries/coverage-map`,
      donor_report: `${ROOTS.DASHBOARD}/beneficiaries/donor-report`,
      attendance_tracker: `${ROOTS.DASHBOARD}/beneficiaries/attendance-tracker`,
      // Settings
      beneficiary_settings: `${ROOTS.DASHBOARD}/beneficiaries/settings`,
    },

    projects: {
      dashboard: `${ROOTS.DASHBOARD}/projects/dashboard`,
      root: `${ROOTS.DASHBOARD}/projects`,
      planning: `${ROOTS.DASHBOARD}/projects/planning`,
      budget_finance: `${ROOTS.DASHBOARD}/projects/budget-finance`,
      me_system: `${ROOTS.DASHBOARD}/projects/me-system`,
      risk_management: `${ROOTS.DASHBOARD}/projects/risk-management`,
      resource_allocation: `${ROOTS.DASHBOARD}/projects/resource-allocation`,
      donor_reporting: `${ROOTS.DASHBOARD}/projects/donor-reporting`,
      stakeholder_management: `${ROOTS.DASHBOARD}/projects/stakeholder-management`,
      document_repository: `${ROOTS.DASHBOARD}/projects/document-repository`,
      project_analytics: `${ROOTS.DASHBOARD}/projects/project-analytics`,
      donors: {
        root: `${ROOTS.DASHBOARD}/projects/donors`,
        create: `${ROOTS.DASHBOARD}/projects/donors/new`,
        detail: (id) => `${ROOTS.DASHBOARD}/projects/donors/${id}`,
        edit: (id) => `${ROOTS.DASHBOARD}/projects/donors/${id}/edit`,
        ledgerCreate: (id) => `${ROOTS.DASHBOARD}/projects/donors/${id}/ledgers/new`,
      },
    },
    storeInventory: {
      root: `${ROOTS.DASHBOARD}/store&inventory`,
      // Dashboard
      dashboard: `${ROOTS.DASHBOARD}/store&inventory/dashboard`,
      // Products
      itemMaster: `${ROOTS.DASHBOARD}/store&inventory/item-master`,
      item_detail: (id) => `${ROOTS.DASHBOARD}/store&inventory/item-master/${id}`,
      add_item: `${ROOTS.DASHBOARD}/store&inventory/item-master/create-item`,
      add_category: `${ROOTS.DASHBOARD}/store&inventory/item-master/category-list`,
      productVariants: `${ROOTS.DASHBOARD}/store&inventory/product-variants`,
      productVariant_detail: (id) => `${ROOTS.DASHBOARD}/store&inventory/product-variants/${id}`,
      unitsOfMeasure: `${ROOTS.DASHBOARD}/store&inventory/units-of-measure`,
      packagingTypes: `${ROOTS.DASHBOARD}/store&inventory/packaging-types`,
      packagingType_detail: (id) => `${ROOTS.DASHBOARD}/store&inventory/packaging-types/${id}`,
      productTemplates: `${ROOTS.DASHBOARD}/store&inventory/product-templates`,
      kittingBom: `${ROOTS.DASHBOARD}/store&inventory/kitting-bom`,
      reorderRules: `${ROOTS.DASHBOARD}/store&inventory/reorder-rules`,
      // Operations
      goodsReceiptNote: `${ROOTS.DASHBOARD}/store&inventory/goods-receipt-note`,
      goodsReceiptNote_detail: (id) =>
        `${ROOTS.DASHBOARD}/store&inventory/goods-receipt-note/${id}`,
      goods_issue_note: `${ROOTS.DASHBOARD}/store&inventory/goods-issue-note`,
      goods_issue_note_create: `${ROOTS.DASHBOARD}/store&inventory/goods-issue-note/create`,
      goods_issue_note_detail: (id) => `${ROOTS.DASHBOARD}/store&inventory/goods-issue-note/${id}`,
      goods_issue_note_edit: (id) =>
        `${ROOTS.DASHBOARD}/store&inventory/goods-issue-note/${id}/edit`,
      stock_transfer: `${ROOTS.DASHBOARD}/store&inventory/stock-transfer`,
      stock_transfer_detail: (id) => `${ROOTS.DASHBOARD}/store&inventory/stock-transfer/${id}`,
      stock_adjustment: `${ROOTS.DASHBOARD}/store&inventory/stock-adjustment`,
      stock_adjustment_create: `${ROOTS.DASHBOARD}/store&inventory/stock-adjustment/create`,
      stock_adjustment_edit: (id) =>
        `${ROOTS.DASHBOARD}/store&inventory/stock-adjustment/${id}/edit`,
      stock_adjustment_detail: (id) => `${ROOTS.DASHBOARD}/store&inventory/stock-adjustment/${id}`,
      location_stocks: `${ROOTS.DASHBOARD}/store&inventory/location-stocks`,
      cycleCounting: `${ROOTS.DASHBOARD}/store&inventory/cycle-counting`,
      returns: `${ROOTS.DASHBOARD}/store&inventory/returns`,
      batchTransfers: `${ROOTS.DASHBOARD}/store&inventory/batch-transfers`,
      scrapManagement: `${ROOTS.DASHBOARD}/store&inventory/scrap-management`,
      scrapManagement_create: `${ROOTS.DASHBOARD}/store&inventory/scrap-management/create`,
      scrapManagement_edit: (id) =>
        `${ROOTS.DASHBOARD}/store&inventory/scrap-management/${id}/edit`,
      scrapManagement_detail: (id) => `${ROOTS.DASHBOARD}/store&inventory/scrap-management/${id}`,
      // Return Management
      returnManagement: `${ROOTS.DASHBOARD}/store&inventory/return-management`,
      returnManagement_create: `${ROOTS.DASHBOARD}/store&inventory/return-management/create`,
      returnManagement_detail: (id) => `${ROOTS.DASHBOARD}/store&inventory/return-management/${id}`,
      returnManagement_history: `${ROOTS.DASHBOARD}/store&inventory/return-management/history`,
      returnManagement_history_detail: (id) =>
        `${ROOTS.DASHBOARD}/store&inventory/return-management/history/${id}`,
      backorders: `${ROOTS.DASHBOARD}/store&inventory/backorders`,
      replenishment: `${ROOTS.DASHBOARD}/store&inventory/replenishment`,
      dropshipping: `${ROOTS.DASHBOARD}/store&inventory/dropshipping`,
      dropshipping_create: `${ROOTS.DASHBOARD}/store&inventory/dropshipping/create`,
      dropshipping_detail: (id) => `${ROOTS.DASHBOARD}/store&inventory/dropshipping/${id}`,
      dropshipping_edit: (id) => `${ROOTS.DASHBOARD}/store&inventory/dropshipping/${id}/edit`,
      crossDocking: `${ROOTS.DASHBOARD}/store&inventory/cross-docking`,
      crossDocking_detail: (id) => `${ROOTS.DASHBOARD}/store&inventory/cross-docking/${id}`,
      // Warehouse & Locations
      warehouses: `${ROOTS.DASHBOARD}/store&inventory/warehouses`,
      warehouse_detail: (id) => `${ROOTS.DASHBOARD}/store&inventory/warehouses/${id}`,
      officeLocations: `${ROOTS.DASHBOARD}/store&inventory/office-locations`,
      storageLocations: `${ROOTS.DASHBOARD}/store&inventory/storage-locations`,
      storage_location_detail: (id) => `${ROOTS.DASHBOARD}/store&inventory/storage-locations/${id}`,
      putawayRules: `${ROOTS.DASHBOARD}/store&inventory/putaway-rules`,
      putawayRule_detail: (id) => `${ROOTS.DASHBOARD}/store&inventory/putaway-rules/${id}`,
      removalStrategies: `${ROOTS.DASHBOARD}/store&inventory/removal-strategies`,
      removalStrategy_detail: (id) => `${ROOTS.DASHBOARD}/store&inventory/removal-strategies/${id}`,
      routesAndRules: `${ROOTS.DASHBOARD}/store&inventory/routes-and-rules`,
      routesAndRules_detail: (id) => `${ROOTS.DASHBOARD}/store&inventory/routes-and-rules/${id}`,
      operationTypes: `${ROOTS.DASHBOARD}/store&inventory/operation-types`,
      operationType_detail: (id) => `${ROOTS.DASHBOARD}/store&inventory/operation-types/${id}`,
      // Lots & Traceability
      lotSerialNumbers: `${ROOTS.DASHBOARD}/store&inventory/lot-serial-numbers`,
      expiryDateTracking: `${ROOTS.DASHBOARD}/store&inventory/expiry-date-tracking`,
      moveHistory: `${ROOTS.DASHBOARD}/store&inventory/move-history`,
      lotTraceability: `${ROOTS.DASHBOARD}/store&inventory/lot-traceability`,
      productRecalls: `${ROOTS.DASHBOARD}/store&inventory/product-recalls`,
      // Quality Control
      qualityChecks: `${ROOTS.DASHBOARD}/store&inventory/quality-checks`,
      qualityCheck_detail: (id) => `${ROOTS.DASHBOARD}/store&inventory/quality-checks/${id}`,
      qualityAlerts: `${ROOTS.DASHBOARD}/store&inventory/quality-alerts`,
      qualityAlert_detail: (id) => `${ROOTS.DASHBOARD}/store&inventory/quality-alerts/${id}`,
      qualityControlPoints: `${ROOTS.DASHBOARD}/store&inventory/quality-control-points`,
      qualityControlPoint_detail: (id) =>
        `${ROOTS.DASHBOARD}/store&inventory/quality-control-points/${id}`,
      qualityTeams: `${ROOTS.DASHBOARD}/store&inventory/quality-teams`,
      qualityTeam_detail: (id) => `${ROOTS.DASHBOARD}/store&inventory/quality-teams/${id}`,
      qcTemplates: `${ROOTS.DASHBOARD}/store&inventory/qc-templates`,
      qcTemplate_detail: (id) => `${ROOTS.DASHBOARD}/store&inventory/qc-templates/${id}`,
      // Valuation & Costing
      inventoryValuation: `${ROOTS.DASHBOARD}/store&inventory/inventory-valuation`,
      landedCosts: `${ROOTS.DASHBOARD}/store&inventory/landed-costs`,
      valuationMethods: `${ROOTS.DASHBOARD}/store&inventory/valuation-methods`,
      stockValuationLayers: `${ROOTS.DASHBOARD}/store&inventory/stock-valuation-layers`,
      // Barcode & Scanning
      barcodeScanning: `${ROOTS.DASHBOARD}/store&inventory/barcode-scanning`,
      labelPrinting: `${ROOTS.DASHBOARD}/store&inventory/label-printing`,
      mobileWarehouse: `${ROOTS.DASHBOARD}/store&inventory/mobile-warehouse`,
      // Reports
      approvals: `${ROOTS.DASHBOARD}/store&inventory/approvals`,
      stock_management: `${ROOTS.DASHBOARD}/store&inventory/stock-management`,
      stock_reports: `${ROOTS.DASHBOARD}/store&inventory/stock-reports`,
      inventoryLog: `${ROOTS.DASHBOARD}/store&inventory/inventory-log`,
      inventoryLogList: `${ROOTS.DASHBOARD}/store&inventory/inventory-log/list`,
      inventoryLogAnalytics: `${ROOTS.DASHBOARD}/store&inventory/inventory-log/analytics`,
      inventoryLogHistory: `${ROOTS.DASHBOARD}/store&inventory/inventory-log/history`,
      inventoryLog_detail: (logId) => `${ROOTS.DASHBOARD}/store&inventory/inventory-log/${logId}`,
      inventoryLogHistory_detail: (logId) =>
        `${ROOTS.DASHBOARD}/store&inventory/inventory-log/history/${logId}`,
      operationInventoryLog: `${ROOTS.DASHBOARD}/store&inventory/operations/inventory-log`,
      operationInventoryLogHistory: `${ROOTS.DASHBOARD}/store&inventory/operations/inventory-log/history`,
      inventory_analytics: `${ROOTS.DASHBOARD}/store&inventory/inventory-analytics`,
      stockMovesHistory: `${ROOTS.DASHBOARD}/store&inventory/stock-moves-history`,
      forecastedStock: `${ROOTS.DASHBOARD}/store&inventory/forecasted-stock`,
      stockAgingReport: `${ROOTS.DASHBOARD}/store&inventory/stock-aging-report`,
      abcAnalysis: `${ROOTS.DASHBOARD}/store&inventory/abc-analysis`,
      consumptionReport: `${ROOTS.DASHBOARD}/store&inventory/consumption-report`,
      wastageReport: `${ROOTS.DASHBOARD}/store&inventory/wastage-report`,
      turnoverAnalysis: `${ROOTS.DASHBOARD}/store&inventory/turnover-analysis`,
      landedCostReport: `${ROOTS.DASHBOARD}/store&inventory/landed-cost-report`,
      // NGO Operations
      donorFundedInventory: `${ROOTS.DASHBOARD}/store&inventory/donor-funded-inventory`,
      fieldDistribution: `${ROOTS.DASHBOARD}/store&inventory/field-distribution`,
      humanitarianKitting: `${ROOTS.DASHBOARD}/store&inventory/humanitarian-kitting`,
      emergencyReserves: `${ROOTS.DASHBOARD}/store&inventory/emergency-reserves`,
      pipelineTracking: `${ROOTS.DASHBOARD}/store&inventory/pipeline-tracking`,
      commodityTracking: `${ROOTS.DASHBOARD}/store&inventory/commodity-tracking`,
      waybillManagement: `${ROOTS.DASHBOARD}/store&inventory/waybill-management`,
      disposalManagement: `${ROOTS.DASHBOARD}/store&inventory/disposal-management`,
      lossDamageClaims: `${ROOTS.DASHBOARD}/store&inventory/loss-damage-claims`,
      beneficiaryDistribution: `${ROOTS.DASHBOARD}/store&inventory/beneficiary-distribution`,
      fieldWarehouse: `${ROOTS.DASHBOARD}/store&inventory/field-warehouse`,
      customsImportTracking: `${ROOTS.DASHBOARD}/store&inventory/customs-import-tracking`,
      vehicleDispatch: `${ROOTS.DASHBOARD}/store&inventory/vehicle-dispatch`,
      // Settings
      warehouseSettings: `${ROOTS.DASHBOARD}/store&inventory/warehouse-settings`,
      warehouseSettingsDetail: (id) =>
        `${ROOTS.DASHBOARD}/store&inventory/warehouse-settings/${id}`,
      officeSettings: `${ROOTS.DASHBOARD}/store&inventory/office-settings`,
      officeSettingsDetail: (id) => `${ROOTS.DASHBOARD}/store&inventory/office-settings/${id}`,
      shippingMethods: `${ROOTS.DASHBOARD}/store&inventory/shipping-methods`,
      packageTypes: `${ROOTS.DASHBOARD}/store&inventory/package-types`,
      inventorySettings: `${ROOTS.DASHBOARD}/store&inventory/inventory-settings`,
      inventoryApprovalMatrix: `${ROOTS.DASHBOARD}/store&inventory/settings/inventory-approval-matrix`,
      approvalWorkflow: `${ROOTS.DASHBOARD}/store&inventory/settings/approval-workflow`,
    },
    procurement_before: {
      root: `${ROOTS.DASHBOARD}/procurement`,
      supplier_management: `${ROOTS.DASHBOARD}/procurement/supplier-management`,
      approvals: `${ROOTS.DASHBOARD}/procurement/approvals`,
      add_supplier: `${ROOTS.DASHBOARD}/procurement/supplier-management/add-supplier`,
      purchase_requisitions: `${ROOTS.DASHBOARD}/procurement/purchase-requisitions`,
      add_purchase_requisition: `${ROOTS.DASHBOARD}/procurement/purchase-requisitions/add-pr`,
      purchase_orders: `${ROOTS.DASHBOARD}/procurement/purchase-orders`,
      add_purchase_order: `${ROOTS.DASHBOARD}/procurement/purchase-orders/add-po`,
      request_for_quotation: `${ROOTS.DASHBOARD}/procurement/request-for-quotation`,
      add_request_for_quotation: `${ROOTS.DASHBOARD}/procurement/request-for-quotation/add-rfq`,
      comparative_statement: `${ROOTS.DASHBOARD}/procurement/comparative-statement`,
      procurement_analytics: `${ROOTS.DASHBOARD}/procurement/procurement-analytics`,
    },
    // procurement: {
    //   root: `${ROOTS.DASHBOARD}/procurement`,
    //   dashboard: `${ROOTS.DASHBOARD}/procurement/dashboard`,
    //   supplier_management: `${ROOTS.DASHBOARD}/procurement/supplier-management`,
    //   approvals: `${ROOTS.DASHBOARD}/procurement/approvals`,
    //   add_supplier: `${ROOTS.DASHBOARD}/procurement/supplier-management/add-supplier`,
    //   purchase_requisitions: `${ROOTS.DASHBOARD}/procurement/purchase-requisitions`,
    //   add_purchase_requisition: `${ROOTS.DASHBOARD}/procurement/purchase-requisitions/add-pr`,
    //   purchase_orders: `${ROOTS.DASHBOARD}/procurement/purchase-orders`,
    //   add_purchase_order: `${ROOTS.DASHBOARD}/procurement/purchase-orders/add-po`,
    //   request_for_quotation: `${ROOTS.DASHBOARD}/procurement/request-for-quotation`,
    //   add_request_for_quotation: `${ROOTS.DASHBOARD}/procurement/request-for-quotation/add-rfq`,
    //   comparative_statement: `${ROOTS.DASHBOARD}/procurement/comparative-statement`,
    //   procurement_analytics: `${ROOTS.DASHBOARD}/procurement/procurement-analytics`,
    //   requisitions: {
    //     root: `${ROOTS.DASHBOARD}/procurement/requisitions`,
    //     list: `${ROOTS.DASHBOARD}/procurement/requisitions/list`,
    //     create: `${ROOTS.DASHBOARD}/procurement/requisitions/create`,
    //     approvals: `${ROOTS.DASHBOARD}/procurement/requisitions/approvals`,
    //     detail: (id) => `${ROOTS.DASHBOARD}/procurement/requisitions/${id}`,
    //     timeline: (id) => `${ROOTS.DASHBOARD}/procurement/requisitions/${id}/timeline`,
    //   },
    //   rfq: {
    //     root: `${ROOTS.DASHBOARD}/procurement/rfq`,
    //     list: `${ROOTS.DASHBOARD}/procurement/rfq/list`,
    //     create: `${ROOTS.DASHBOARD}/procurement/rfq/create`,
    //     detail: (id) => `${ROOTS.DASHBOARD}/procurement/rfq/${id}`,
    //     distribution: `${ROOTS.DASHBOARD}/procurement/rfq/distribution`,
    //     monitoring: `${ROOTS.DASHBOARD}/procurement/rfq/monitoring`,
    //   },
    //   quotations: {
    //     root: `${ROOTS.DASHBOARD}/procurement/quotations`,
    //     list: `${ROOTS.DASHBOARD}/procurement/quotations/list`,
    //     opening: (id) => `${ROOTS.DASHBOARD}/procurement/quotations/opening/${id}`,
    //   },
    //   comparative: {
    //     root: `${ROOTS.DASHBOARD}/procurement/comparative`,
    //     list: `${ROOTS.DASHBOARD}/procurement/comparative/list`,
    //     detail: (id) => `${ROOTS.DASHBOARD}/procurement/comparative/${id}`,
    //     approval: (id) => `${ROOTS.DASHBOARD}/procurement/comparative/${id}/approval`,
    //     print: (id) => `${ROOTS.DASHBOARD}/procurement/comparative/${id}/print`,
    //   },
    //   awards: {
    //     root: `${ROOTS.DASHBOARD}/procurement/awards`,
    //     summary: `${ROOTS.DASHBOARD}/procurement/awards/summary`,
    //     notification: (id) => `${ROOTS.DASHBOARD}/procurement/awards/notification/${id}`,
    //     history: `${ROOTS.DASHBOARD}/procurement/awards/history`,
    //     vendorView: (id) => `${ROOTS.DASHBOARD}/procurement/awards/vendor-view/${id}`,
    //   },
    //   workOrders: {
    //     root: `${ROOTS.DASHBOARD}/procurement/work-orders`,
    //     list: `${ROOTS.DASHBOARD}/procurement/work-orders/list`,
    //     create: `${ROOTS.DASHBOARD}/procurement/work-orders/create`,
    //     detail: (id) => `${ROOTS.DASHBOARD}/procurement/work-orders/${id}`,
    //     approval: (id) => `${ROOTS.DASHBOARD}/procurement/work-orders/${id}/approval`,
    //     print: (id) => `${ROOTS.DASHBOARD}/procurement/work-orders/${id}/print`,
    //     vendorAcceptance: (id) =>
    //       `${ROOTS.DASHBOARD}/procurement/work-orders/vendor-acceptance/${id}`,
    //   },
    //   grn: {
    //     root: `${ROOTS.DASHBOARD}/procurement/grn`,
    //     list: `${ROOTS.DASHBOARD}/procurement/grn/list`,
    //     create: `${ROOTS.DASHBOARD}/procurement/grn/create`,
    //     detail: (id) => `${ROOTS.DASHBOARD}/procurement/grn/${id}`,
    //     verify: (id) => `${ROOTS.DASHBOARD}/procurement/grn/${id}/verify`,
    //   },
    //   inventory: {
    //     root: `${ROOTS.DASHBOARD}/procurement/inventory`,
    //     dashboard: `${ROOTS.DASHBOARD}/procurement/inventory/dashboard`,
    //     items: `${ROOTS.DASHBOARD}/procurement/inventory/items`,
    //     detail: (id) => `${ROOTS.DASHBOARD}/procurement/inventory/detail/${id}`,
    //     assetDetail: (id) => `${ROOTS.DASHBOARD}/procurement/inventory/asset-detail/${id}`,
    //     consumableDetail: (id) =>
    //       `${ROOTS.DASHBOARD}/procurement/inventory/consumable-detail/${id}`,
    //     movement: `${ROOTS.DASHBOARD}/procurement/inventory/movement`,
    //     issue: `${ROOTS.DASHBOARD}/procurement/inventory/issue`,
    //   },
    //   paymentRequisitions: {
    //     root: `${ROOTS.DASHBOARD}/procurement/payment-requisitions`,
    //     list: `${ROOTS.DASHBOARD}/procurement/payment-requisitions/list`,
    //     create: `${ROOTS.DASHBOARD}/procurement/payment-requisitions/create`,
    //     detail: (id) => `${ROOTS.DASHBOARD}/procurement/payment-requisitions/${id}`,
    //     approve: (id) => `${ROOTS.DASHBOARD}/procurement/payment-requisitions/${id}/approve`,
    //   },
    //   treasury: {
    //     root: `${ROOTS.DASHBOARD}/procurement/treasury`,
    //     financeReview: `${ROOTS.DASHBOARD}/procurement/treasury/finance-review`,
    //     processing: `${ROOTS.DASHBOARD}/procurement/treasury/processing`,
    //     processingDetail: (id) => `${ROOTS.DASHBOARD}/procurement/treasury/processing/${id}`,
    //     timeline: `${ROOTS.DASHBOARD}/procurement/treasury/timeline`,
    //     timelineDetail: (id) => `${ROOTS.DASHBOARD}/procurement/treasury/timeline/${id}`,
    //     analytics: `${ROOTS.DASHBOARD}/procurement/treasury/analytics`,
    //   },
    //   vendors: {
    //     root: `${ROOTS.DASHBOARD}/procurement/vendors`,
    //     list: `${ROOTS.DASHBOARD}/procurement/vendors/list`,
    //     create: `${ROOTS.DASHBOARD}/procurement/vendors/create`,
    //     categories: `${ROOTS.DASHBOARD}/procurement/vendors/categories`,
    //     performance: `${ROOTS.DASHBOARD}/procurement/vendors/performance`,
    //     evaluation: `${ROOTS.DASHBOARD}/procurement/vendors/evaluation`,
    //     onboarding: `${ROOTS.DASHBOARD}/procurement/vendors/onboarding`,
    //     detail: (id) => `${ROOTS.DASHBOARD}/procurement/vendors/detail/${id}`,
    //     verification: `${ROOTS.DASHBOARD}/procurement/vendors/verification`,
    //     categoryMapping: `${ROOTS.DASHBOARD}/procurement/vendors/category-mapping`,
    //   },
    //   reports: {
    //     root: `${ROOTS.DASHBOARD}/procurement/reports`,
    //     requisitions: `${ROOTS.DASHBOARD}/procurement/reports/requisitions`,
    //     rfq: `${ROOTS.DASHBOARD}/procurement/reports/rfq`,
    //     vendorParticipation: `${ROOTS.DASHBOARD}/procurement/reports/vendor-participation`,
    //     vendorAwards: `${ROOTS.DASHBOARD}/procurement/reports/vendor-awards`,
    //     workOrders: `${ROOTS.DASHBOARD}/procurement/reports/work-orders`,
    //     inventoryReceived: `${ROOTS.DASHBOARD}/procurement/reports/inventory-received`,
    //     fixedAssets: `${ROOTS.DASHBOARD}/procurement/reports/fixed-assets`,
    //     consumables: `${ROOTS.DASHBOARD}/procurement/reports/consumables`,
    //     payments: `${ROOTS.DASHBOARD}/procurement/reports/payments`,
    //     budget: `${ROOTS.DASHBOARD}/procurement/reports/budget`,
    //   },
    //   notifications: `${ROOTS.DASHBOARD}/procurement/notifications`,
    //   procurementSettings: {
    //     root: `${ROOTS.DASHBOARD}/procurement/settings`,
    //     users: `${ROOTS.DASHBOARD}/procurement/settings/users`,
    //     roles: `${ROOTS.DASHBOARD}/procurement/settings/roles`,
    //     approvalMatrix: `${ROOTS.DASHBOARD}/procurement/settings/approval-matrix`,
    //     budgetCodes: `${ROOTS.DASHBOARD}/procurement/settings/budget-codes`,
    //     accountCodes: `${ROOTS.DASHBOARD}/procurement/settings/account-codes`,
    //     categories: `${ROOTS.DASHBOARD}/procurement/settings/categories`,
    //     items: `${ROOTS.DASHBOARD}/procurement/settings/items`,
    //     emailTemplates: `${ROOTS.DASHBOARD}/procurement/settings/email-templates`,
    //     notifications: `${ROOTS.DASHBOARD}/procurement/settings/notifications`,
    //   },
    // },
    procurement: {
      root: `${ROOTS.DASHBOARD}/procurement`,
      dashboard: `${ROOTS.DASHBOARD}/procurement/dashboard`,
      requisitions: {
        root: `${ROOTS.DASHBOARD}/procurement/requisitions`,
        list: `${ROOTS.DASHBOARD}/procurement/requisitions/list`,
        create: `${ROOTS.DASHBOARD}/procurement/requisitions/create`,
        detail: (id) => `${ROOTS.DASHBOARD}/procurement/requisitions/${id}`,
        timeline: (id) => `${ROOTS.DASHBOARD}/procurement/requisitions/${id}/timeline`,
        workflowApproval: `${ROOTS.DASHBOARD}/procurement/requisitions/workflow-approval`,
      },
      rfq: {
        root: `${ROOTS.DASHBOARD}/procurement/rfq`,
        list: `${ROOTS.DASHBOARD}/procurement/rfq/list`,
        create: `${ROOTS.DASHBOARD}/procurement/rfq/create`,
        detail: (id) => `${ROOTS.DASHBOARD}/procurement/rfq/${id}`,
        distribution: `${ROOTS.DASHBOARD}/procurement/rfq/distribution`,
        monitoring: `${ROOTS.DASHBOARD}/procurement/rfq/monitoring`,
      },
      quotations: {
        root: `${ROOTS.DASHBOARD}/procurement/quotations`,
        list: `${ROOTS.DASHBOARD}/procurement/quotations/list`,
        opening: (id) => `${ROOTS.DASHBOARD}/procurement/quotations/opening/${id}`,
        directEvaluation: `${ROOTS.DASHBOARD}/procurement/quotations/direct-evaluation`,
        manualSubmitQuotation: `${ROOTS.DASHBOARD}/procurement/quotations/manual-submit-quotation`,
      },
      comparative: {
        root: `${ROOTS.DASHBOARD}/procurement/comparative`,
        list: `${ROOTS.DASHBOARD}/procurement/comparative/list`,
        pending: `${ROOTS.DASHBOARD}/procurement/comparative/list?mode=pending`,
        detail: (id) => `${ROOTS.DASHBOARD}/procurement/comparative/${id}`,
        approval: (id) => `${ROOTS.DASHBOARD}/procurement/comparative/${id}/approval`,
        print: (id) => `${ROOTS.DASHBOARD}/procurement/comparative/${id}/print`,
      },
      awards: {
        root: `${ROOTS.DASHBOARD}/procurement/awards`,
        summary: `${ROOTS.DASHBOARD}/procurement/awards/summary`,
        notification: (id) => `${ROOTS.DASHBOARD}/procurement/awards/notification/${id}`,
        history: `${ROOTS.DASHBOARD}/procurement/awards/history`,
        vendorView: (id) => `${ROOTS.DASHBOARD}/procurement/awards/vendor-view/${id}`,
      },
      workOrders: {
        root: `${ROOTS.DASHBOARD}/procurement/work-orders`,
        list: `${ROOTS.DASHBOARD}/procurement/work-orders/list`,
        pendingApprovals: `${ROOTS.DASHBOARD}/procurement/work-orders/pending`,
        create: `${ROOTS.DASHBOARD}/procurement/work-orders/create`,
        edit: (id) => `${ROOTS.DASHBOARD}/procurement/work-orders/${id}/edit`,
        detail: (id) => `${ROOTS.DASHBOARD}/procurement/work-orders/${id}`,
        approval: (id) => `${ROOTS.DASHBOARD}/procurement/work-orders/${id}/approval`,
        print: (id) => `${ROOTS.DASHBOARD}/procurement/work-orders/${id}/print`,
        vendorAcceptance: (id) =>
          `${ROOTS.DASHBOARD}/procurement/work-orders/vendor-acceptance/${id}`,
      },
      directPurchase: {
        root: `${ROOTS.DASHBOARD}/procurement/direct-purchase`,
        list: `${ROOTS.DASHBOARD}/procurement/direct-purchase/list`,
        pendingApprovals: `${ROOTS.DASHBOARD}/procurement/direct-purchase/pending`,
        create: `${ROOTS.DASHBOARD}/procurement/direct-purchase/create`,
        detail: (id) => `${ROOTS.DASHBOARD}/procurement/direct-purchase/${id}`,
      },
      grn: {
        root: `${ROOTS.DASHBOARD}/procurement/grn`,
        list: `${ROOTS.DASHBOARD}/procurement/grn/list`,
        pendingVerification: `${ROOTS.DASHBOARD}/procurement/grn/pending`,
        create: `${ROOTS.DASHBOARD}/procurement/grn/create`,
        detail: (id) => `${ROOTS.DASHBOARD}/procurement/grn/${id}`,
        verify: (id) => `${ROOTS.DASHBOARD}/procurement/grn/${id}/verify`,
      },
      inventory: {
        root: `${ROOTS.DASHBOARD}/procurement/inventory`,
        dashboard: `${ROOTS.DASHBOARD}/procurement/inventory/dashboard`,
        items: `${ROOTS.DASHBOARD}/procurement/inventory/items`,
        detail: (id) => `${ROOTS.DASHBOARD}/procurement/inventory/detail/${id}`,
        assetDetail: (id) => `${ROOTS.DASHBOARD}/procurement/inventory/asset-detail/${id}`,
        consumableDetail: (id) =>
          `${ROOTS.DASHBOARD}/procurement/inventory/consumable-detail/${id}`,
        movement: `${ROOTS.DASHBOARD}/procurement/inventory/movement`,
        issue: `${ROOTS.DASHBOARD}/procurement/inventory/issue`,
        warehouses: `${ROOTS.DASHBOARD}/procurement/inventory/warehouses`,
        warehouseDetail: (id) => `${ROOTS.DASHBOARD}/procurement/inventory/warehouses/${id}`,
        interWarehouseTransfer: `${ROOTS.DASHBOARD}/procurement/inventory/inter-warehouse-transfer`,
        materialRequisition: `${ROOTS.DASHBOARD}/procurement/inventory/material-requisition`,
        materialRelease: `${ROOTS.DASHBOARD}/procurement/inventory/material-release`,
        reports: `${ROOTS.DASHBOARD}/procurement/inventory/reports`,
      },
      paymentRequisitions: {
        root: `${ROOTS.DASHBOARD}/procurement/payment-requisitions`,
        list: `${ROOTS.DASHBOARD}/procurement/payment-requisitions/list`,
        listApproved: `${ROOTS.DASHBOARD}/procurement/payment-requisitions/list?status=Approved`,
        listAll: `${ROOTS.DASHBOARD}/procurement/payment-requisitions/list?status=all`,
        pendingApprovals: `${ROOTS.DASHBOARD}/procurement/payment-requisitions/list?status=Pending%20Approval`,
        paymentSchedule: `${ROOTS.DASHBOARD}/procurement/payment-requisitions/list?view=schedule`,
        create: `${ROOTS.DASHBOARD}/procurement/payment-requisitions/create`,
        detail: (id) => `${ROOTS.DASHBOARD}/procurement/payment-requisitions/${id}`,
        approve: (id) => `${ROOTS.DASHBOARD}/procurement/payment-requisitions/${id}/approve`,
      },
      treasury: {
        root: `${ROOTS.DASHBOARD}/procurement/treasury`,
        financeReview: `${ROOTS.DASHBOARD}/procurement/treasury/finance-review`,
        processing: `${ROOTS.DASHBOARD}/procurement/treasury/processing`,
        processingDetail: (id) => `${ROOTS.DASHBOARD}/procurement/treasury/processing/${id}`,
        timeline: `${ROOTS.DASHBOARD}/procurement/treasury/timeline`,
        timelineDetail: (id) => `${ROOTS.DASHBOARD}/procurement/treasury/timeline/${id}`,
        analytics: `${ROOTS.DASHBOARD}/procurement/treasury/analytics`,
        bankReconciliation: `${ROOTS.DASHBOARD}/procurement/treasury/bank-reconciliation`,
        bankReconciliationDetail: (id) =>
          `${ROOTS.DASHBOARD}/procurement/treasury/bank-reconciliation/${id}`,
      },
      vendors: {
        root: `${ROOTS.DASHBOARD}/procurement/vendors`,
        list: `${ROOTS.DASHBOARD}/procurement/vendors/list`,
        create: `${ROOTS.DASHBOARD}/procurement/vendors/create`,
        categories: `${ROOTS.DASHBOARD}/procurement/vendors/categories`,
        performance: `${ROOTS.DASHBOARD}/procurement/vendors/performance`,
        evaluation: `${ROOTS.DASHBOARD}/procurement/vendors/evaluation`,
        onboarding: `${ROOTS.DASHBOARD}/procurement/vendors/onboarding`,
        detail: (id) => `${ROOTS.DASHBOARD}/procurement/vendors/detail/${id}`,
        verification: `${ROOTS.DASHBOARD}/procurement/vendors/verification`,
        categoryMapping: `${ROOTS.DASHBOARD}/procurement/vendors/category-mapping`,
        blacklist: `${ROOTS.DASHBOARD}/procurement/vendors/blacklist`,
        blacklistRequest: `${ROOTS.DASHBOARD}/procurement/vendors/blacklist/request`,
        enlistment: `${ROOTS.DASHBOARD}/procurement/vendors/enlistment`,
        enlistmentNew: `${ROOTS.DASHBOARD}/procurement/vendors/enlistment/new`,
        enlistmentReview: (id) => `${ROOTS.DASHBOARD}/procurement/vendors/enlistment/${id}/review`,
      },
      reports: {
        root: `${ROOTS.DASHBOARD}/procurement/reports`,
        requisitions: `${ROOTS.DASHBOARD}/procurement/reports/requisitions`,
        rfq: `${ROOTS.DASHBOARD}/procurement/reports/rfq`,
        vendorParticipation: `${ROOTS.DASHBOARD}/procurement/reports/vendor-participation`,
        vendorAwards: `${ROOTS.DASHBOARD}/procurement/reports/vendor-awards`,
        workOrders: `${ROOTS.DASHBOARD}/procurement/reports/work-orders`,
        inventoryReceived: `${ROOTS.DASHBOARD}/procurement/reports/inventory-received`,
        fixedAssets: `${ROOTS.DASHBOARD}/procurement/reports/fixed-assets`,
        consumables: `${ROOTS.DASHBOARD}/procurement/reports/consumables`,
        payments: `${ROOTS.DASHBOARD}/procurement/reports/payments`,
        budget: `${ROOTS.DASHBOARD}/procurement/reports/budget`,
        comparativeStatements: `${ROOTS.DASHBOARD}/procurement/reports/comparative-statements`,
        auditLogs: `${ROOTS.DASHBOARD}/procurement/reports/audit-logs`,
        projectProcurement: `${ROOTS.DASHBOARD}/procurement/reports/project-procurement`,
      },
      notifications: `${ROOTS.DASHBOARD}/procurement/notifications`,
      settings: {
        root: `${ROOTS.DASHBOARD}/procurement/settings`,
        users: `${ROOTS.DASHBOARD}/procurement/settings/users`,
        roles: `${ROOTS.DASHBOARD}/procurement/settings/roles`,
        approvalMatrix: `${ROOTS.DASHBOARD}/procurement/settings/approval-matrix`,
        budgetCodes: `${ROOTS.DASHBOARD}/procurement/settings/budget-codes`,
        accountCategories: `${ROOTS.DASHBOARD}/procurement/settings/account-categories`,
        accountCodes: `${ROOTS.DASHBOARD}/procurement/settings/account-codes`,
        categories: `${ROOTS.DASHBOARD}/procurement/settings/categories`,
        items: `${ROOTS.DASHBOARD}/procurement/settings/items`,
        emailTemplates: `${ROOTS.DASHBOARD}/procurement/settings/email-templates`,
        notifications: `${ROOTS.DASHBOARD}/procurement/settings/notifications`,
        offices: `${ROOTS.DASHBOARD}/procurement/settings/offices`,
        officeDetail: (id) => `${ROOTS.DASHBOARD}/procurement/settings/offices/${id}`,
        delegation: `${ROOTS.DASHBOARD}/procurement/settings/delegation`,
        escalation: `${ROOTS.DASHBOARD}/procurement/settings/escalation`,
        fiscalYear: `${ROOTS.DASHBOARD}/procurement/settings/fiscal-year`,
        currency: `${ROOTS.DASHBOARD}/procurement/settings/currency`,
        systemLogs: `${ROOTS.DASHBOARD}/procurement/settings/system-logs`,
        backup: `${ROOTS.DASHBOARD}/procurement/settings/backup`,
      },
      audit: {
        root: `${ROOTS.DASHBOARD}/procurement/audit`,
        log: `${ROOTS.DASHBOARD}/procurement/audit/log`,
        detail: (id) => `${ROOTS.DASHBOARD}/procurement/audit/${id}`,
        compliance: `${ROOTS.DASHBOARD}/procurement/audit/compliance`,
        export: `${ROOTS.DASHBOARD}/procurement/audit/export`,
      },
      documents: {
        root: `${ROOTS.DASHBOARD}/procurement/documents`,
        repository: `${ROOTS.DASHBOARD}/procurement/documents/repository`,
        detail: (id) => `${ROOTS.DASHBOARD}/procurement/documents/${id}`,
        categories: `${ROOTS.DASHBOARD}/procurement/documents/categories`,
        accessControl: `${ROOTS.DASHBOARD}/procurement/documents/access-control`,
      },
      contracts: {
        root: `${ROOTS.DASHBOARD}/procurement/contracts`,
        list: `${ROOTS.DASHBOARD}/procurement/contracts/list`,
        create: `${ROOTS.DASHBOARD}/procurement/contracts/create`,
        detail: (id) => `${ROOTS.DASHBOARD}/procurement/contracts/${id}`,
        amendment: (id) => `${ROOTS.DASHBOARD}/procurement/contracts/${id}/amendment`,
        renewal: (id) => `${ROOTS.DASHBOARD}/procurement/contracts/${id}/renewal`,
      },
      budget: {
        root: `${ROOTS.DASHBOARD}/procurement/budget`,
        planning: `${ROOTS.DASHBOARD}/procurement/budget/planning`,
        utilization: `${ROOTS.DASHBOARD}/procurement/budget/utilization`,
        transfer: `${ROOTS.DASHBOARD}/procurement/budget/transfer`,
        detail: (id) => `${ROOTS.DASHBOARD}/procurement/budget/${id}`,
      },
    },
    vendorPortal: {
      root: '/vendor-portal',
      dashboard: '/vendor-portal/dashboard',
      opportunities: '/vendor-portal/opportunities',
      apply: (id) => `/vendor-portal/apply/${id}`,
      applications: '/vendor-portal/applications',
      quotations: '/vendor-portal/quotations',
      profile: '/vendor-portal/profile',
      documents: '/vendor-portal/documents',
      awards: '/vendor-portal/awards',
      workOrders: '/vendor-portal/work-orders',
      delivery: '/vendor-portal/delivery',
      payments: '/vendor-portal/payments',
      compliance: '/vendor-portal/compliance',
      notifications: '/vendor-portal/notifications',
      support: '/vendor-portal/support',
      statement: '/vendor-portal/statement',
    },
    // â”€â”€ PROJECT MANAGEMENT (ClickUp-style) â”€â”€
    projectManagement: {
      root: `${ROOTS.DASHBOARD}/project-management`,
      dashboard: `${ROOTS.DASHBOARD}/project-management/dashboard`,
      // Workspaces & Spaces
      workspaces: {
        root: `${ROOTS.DASHBOARD}/project-management/workspaces`,
        detail: (id) => `${ROOTS.DASHBOARD}/project-management/workspaces/${id}`,
      },
      spaces: {
        root: `${ROOTS.DASHBOARD}/project-management/spaces`,
        detail: (id) => `${ROOTS.DASHBOARD}/project-management/spaces/${id}`,
        create: `${ROOTS.DASHBOARD}/project-management/spaces/create`,
      },
      // Lists & Tasks
      lists: {
        root: `${ROOTS.DASHBOARD}/project-management/lists`,
        detail: (id) => `${ROOTS.DASHBOARD}/project-management/lists/${id}`,
      },
      tasks: {
        root: `${ROOTS.DASHBOARD}/project-management/tasks`,
        list: `${ROOTS.DASHBOARD}/project-management/tasks/list`,
        board: `${ROOTS.DASHBOARD}/project-management/tasks/board`,
        create: `${ROOTS.DASHBOARD}/project-management/tasks/create`,
        detail: (id) => `${ROOTS.DASHBOARD}/project-management/tasks/${id}`,
        calendar: `${ROOTS.DASHBOARD}/project-management/tasks/calendar`,
        gantt: `${ROOTS.DASHBOARD}/project-management/tasks/gantt`,
        timeline: `${ROOTS.DASHBOARD}/project-management/tasks/timeline`,
        table: `${ROOTS.DASHBOARD}/project-management/tasks/table`,
      },
      // Sprints (Agile)
      sprints: {
        root: `${ROOTS.DASHBOARD}/project-management/sprints`,
        board: `${ROOTS.DASHBOARD}/project-management/sprints/board`,
        backlog: `${ROOTS.DASHBOARD}/project-management/sprints/backlog`,
        retrospective: `${ROOTS.DASHBOARD}/project-management/sprints/retrospective`,
      },
      // Time Tracking
      timeTracking: {
        root: `${ROOTS.DASHBOARD}/project-management/time-tracking`,
        timesheets: `${ROOTS.DASHBOARD}/project-management/time-tracking/timesheets`,
        reports: `${ROOTS.DASHBOARD}/project-management/time-tracking/reports`,
        workload: `${ROOTS.DASHBOARD}/project-management/time-tracking/workload`,
      },
      // Goals & OKRs
      goals: {
        root: `${ROOTS.DASHBOARD}/project-management/goals`,
        create: `${ROOTS.DASHBOARD}/project-management/goals/create`,
        detail: (id) => `${ROOTS.DASHBOARD}/project-management/goals/${id}`,
      },
      // Docs & Wiki
      docs: {
        root: `${ROOTS.DASHBOARD}/project-management/docs`,
        create: `${ROOTS.DASHBOARD}/project-management/docs/create`,
        detail: (id) => `${ROOTS.DASHBOARD}/project-management/docs/${id}`,
      },
      // Automations
      automations: {
        root: `${ROOTS.DASHBOARD}/project-management/automations`,
        create: `${ROOTS.DASHBOARD}/project-management/automations/create`,
      },
      // Dashboards & Reports
      reports: {
        root: `${ROOTS.DASHBOARD}/project-management/reports`,
        custom: `${ROOTS.DASHBOARD}/project-management/reports/custom`,
      },
      // Team & Members
      team: {
        root: `${ROOTS.DASHBOARD}/project-management/team`,
        members: `${ROOTS.DASHBOARD}/project-management/team/members`,
        roles: `${ROOTS.DASHBOARD}/project-management/team/roles`,
      },
      // Templates
      templates: {
        root: `${ROOTS.DASHBOARD}/project-management/templates`,
      },
      // Notifications
      notifications: `${ROOTS.DASHBOARD}/project-management/notifications`,
      // Whiteboards
      whiteboards: {
        root: `${ROOTS.DASHBOARD}/project-management/whiteboards`,
        detail: (id) => `${ROOTS.DASHBOARD}/project-management/whiteboards/${id}`,
      },
      // Forms
      forms: {
        root: `${ROOTS.DASHBOARD}/project-management/forms`,
        create: `${ROOTS.DASHBOARD}/project-management/forms/create`,
        detail: (id) => `${ROOTS.DASHBOARD}/project-management/forms/${id}`,
      },
      // Milestones
      milestones: {
        root: `${ROOTS.DASHBOARD}/project-management/milestones`,
      },
      // Saved Views
      views: {
        root: `${ROOTS.DASHBOARD}/project-management/views`,
      },
      // Activity Log
      activity: `${ROOTS.DASHBOARD}/project-management/activity`,
      // Favorites
      favorites: `${ROOTS.DASHBOARD}/project-management/favorites`,
      // Inbox
      inbox: `${ROOTS.DASHBOARD}/project-management/inbox`,
      // Import / Export
      importExport: `${ROOTS.DASHBOARD}/project-management/import-export`,
      // Settings
      settings: {
        root: `${ROOTS.DASHBOARD}/project-management/settings`,
        general: `${ROOTS.DASHBOARD}/project-management/settings/general`,
        statuses: `${ROOTS.DASHBOARD}/project-management/settings/statuses`,
        customFields: `${ROOTS.DASHBOARD}/project-management/settings/custom-fields`,
        integrations: `${ROOTS.DASHBOARD}/project-management/settings/integrations`,
        import: `${ROOTS.DASHBOARD}/project-management/settings/import`,
        export: `${ROOTS.DASHBOARD}/project-management/settings/export`,
      },
    },
    // projectManagements: {
    //   root: `${ROOTS.DASHBOARD}/project-managements`,
    //   dashboard: `${ROOTS.DASHBOARD}/project-managements/dashboard`,
    //   projects: {
    //     root: `${ROOTS.DASHBOARD}/project-managements/projects`,
    //     allProjects: `${ROOTS.DASHBOARD}/project-managements/projects/all-projects`,
    //     create: `${ROOTS.DASHBOARD}/project-managements/projects/new`,
    //     report: `${ROOTS.DASHBOARD}/project-managements/projects/report`,
    //     detail: (id) => `${ROOTS.DASHBOARD}/project-managements/projects/${id}`,
    //     edit: (id) => `${ROOTS.DASHBOARD}/project-managements/projects/${id}/edit`,
    //   },
    //   taskManagement: {
    //     root: `${ROOTS.DASHBOARD}/project-managements/task-management`,
    //     allTasks: `${ROOTS.DASHBOARD}/project-managements/task-management/all-tasks`,
    //     detail: (projectId, taskId) =>
    //       `${ROOTS.DASHBOARD}/project-managements/task-management/all-tasks/${projectId}/${taskId}`,
    //   },
    // },
    // â”€â”€ ACCOUNTING & FINANCE (Odoo-style) â”€â”€
    accountingFinance: {
      root: `${ROOTS.DASHBOARD}/accounting-finance`,
      dashboard: `${ROOTS.DASHBOARD}/accounting-finance/dashboard`,
      // Configuration
      configuration: {
        root: `${ROOTS.DASHBOARD}/accounting-finance/configuration`,
        chartOfAccounts: `${ROOTS.DASHBOARD}/accounting-finance/configuration/chart-of-accounts`,
        coaList: `${ROOTS.DASHBOARD}/accounting-finance/configuration/coa-list`,
        accountTypes: `${ROOTS.DASHBOARD}/accounting-finance/configuration/account-types`,
        journals: `${ROOTS.DASHBOARD}/accounting-finance/configuration/journals`,
        fiscalYear: `${ROOTS.DASHBOARD}/accounting-finance/configuration/fiscal-year`,
        fiscalPeriods: `${ROOTS.DASHBOARD}/accounting-finance/configuration/fiscal-periods`,
        paymentTerms: `${ROOTS.DASHBOARD}/accounting-finance/configuration/payment-terms`,
        taxes: `${ROOTS.DASHBOARD}/accounting-finance/configuration/taxes`,
        currencies: `${ROOTS.DASHBOARD}/accounting-finance/configuration/currencies`,
        costCenters: `${ROOTS.DASHBOARD}/accounting-finance/configuration/cost-centers`,
        budgetSetup: `${ROOTS.DASHBOARD}/accounting-finance/configuration/budget-setup`,
        assetCategories: `${ROOTS.DASHBOARD}/accounting-finance/configuration/asset-categories`,
        bankCashAccounts: `${ROOTS.DASHBOARD}/accounting-finance/configuration/bank-cash-accounts`,
        fiscalPositions: `${ROOTS.DASHBOARD}/accounting-finance/configuration/fiscal-positions`,
        reconciliationModels: `${ROOTS.DASHBOARD}/accounting-finance/configuration/reconciliation-models`,
        paymentMethods: `${ROOTS.DASHBOARD}/accounting-finance/configuration/payment-methods`,
        incoterms: `${ROOTS.DASHBOARD}/accounting-finance/configuration/incoterms`,
        currencyExchangeRates: `${ROOTS.DASHBOARD}/accounting-finance/configuration/currency-exchange-rates`,
        lockDates: `${ROOTS.DASHBOARD}/accounting-finance/configuration/lock-dates`,
        perdium: `${ROOTS.DASHBOARD}/accounting-finance/configuration/perdium`,
        perdiumDetail: (id) => `${ROOTS.DASHBOARD}/accounting-finance/configuration/perdium/${id}`,
        perdiumClaim: `${ROOTS.DASHBOARD}/accounting-finance/configuration/perdium-claim`,
        perdiumClaimCreate: `${ROOTS.DASHBOARD}/accounting-finance/configuration/perdium-claim/create`,
        perdiumClaimDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/configuration/perdium-claim/${id}`,
      },
      // Transactions
      transactions: {
        root: `${ROOTS.DASHBOARD}/accounting-finance/transactions`,
        journalEntries: `${ROOTS.DASHBOARD}/accounting-finance/transactions/journal-entries`,
        journalEntryDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/transactions/journal-entries/${id}`,
        vouchers: `${ROOTS.DASHBOARD}/accounting-finance/transactions/vouchers`,
        voucherDetail: (id) => `${ROOTS.DASHBOARD}/accounting-finance/transactions/vouchers/${id}`,
        generalLedgerPosting: `${ROOTS.DASHBOARD}/accounting-finance/transactions/general-ledger-posting`,
        generalLedgerPostingDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/transactions/general-ledger-posting/${id}`,
        generalLedgerItemDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/transactions/general-ledger-posting/item/${id}`,
        customerInvoices: `${ROOTS.DASHBOARD}/accounting-finance/transactions/customer-invoices`,
        invoiceDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/transactions/customer-invoices/${id}`,
        creditNotes: `${ROOTS.DASHBOARD}/accounting-finance/transactions/credit-notes`,
        creditNoteDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/transactions/credit-notes/${id}`,
        vendorBills: `${ROOTS.DASHBOARD}/accounting-finance/transactions/vendor-bills`,
        billDetail: (id) => `${ROOTS.DASHBOARD}/accounting-finance/transactions/vendor-bills/${id}`,
        vendorBillDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/transactions/vendor-bills/${id}`,
        debitNotes: `${ROOTS.DASHBOARD}/accounting-finance/transactions/debit-notes`,
        debitNoteDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/transactions/debit-notes/${id}`,
        customerReceipts: `${ROOTS.DASHBOARD}/accounting-finance/transactions/customer-receipts`,
        customerReceiptDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/transactions/customer-receipts/${id}`,
        supplierPayments: `${ROOTS.DASHBOARD}/accounting-finance/transactions/supplier-payments`,
        supplierPaymentDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/transactions/supplier-payments/${id}`,
        bankDeposits: `${ROOTS.DASHBOARD}/accounting-finance/transactions/bank-deposits`,
        bankDepositDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/transactions/bank-deposits/${id}`,
        cashTransactions: `${ROOTS.DASHBOARD}/accounting-finance/transactions/cash-transactions`,
        cashTransactionDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/transactions/cash-transactions/${id}`,
        contraEntries: `${ROOTS.DASHBOARD}/accounting-finance/transactions/contra-entries`,
        contraEntryDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/transactions/contra-entries/${id}`,
        expenseEntries: `${ROOTS.DASHBOARD}/accounting-finance/transactions/expense-entries`,
        expenseEntryDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/transactions/expense-entries/${id}`,
        payrollEntries: `${ROOTS.DASHBOARD}/accounting-finance/transactions/payroll-entries`,
        payrollEntryDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/transactions/payroll-entries/${id}`,
        inventoryEntries: `${ROOTS.DASHBOARD}/accounting-finance/transactions/inventory-entries`,
        inventoryEntryDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/transactions/inventory-entries/${id}`,
        journalItems: `${ROOTS.DASHBOARD}/accounting-finance/transactions/journal-items`,
        journalItemDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/transactions/journal-items/${id}`,
        deferredRevenue: `${ROOTS.DASHBOARD}/accounting-finance/transactions/deferred-revenue`,
        deferredRevenueDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/transactions/deferred-revenue/${id}`,
        deferredExpenses: `${ROOTS.DASHBOARD}/accounting-finance/transactions/deferred-expenses`,
        deferredExpenseDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/transactions/deferred-expenses/${id}`,
        travelExpense: `${ROOTS.DASHBOARD}/accounting-finance/transactions/travel-expence`,
        travelExpenseCreate: `${ROOTS.DASHBOARD}/accounting-finance/transactions/travel-expence/create`,
        travelExpenseDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/transactions/travel-expence/${id}`,
      },
      // Banking
      banking: {
        root: `${ROOTS.DASHBOARD}/accounting-finance/banking`,
        bankAccounts: `${ROOTS.DASHBOARD}/accounting-finance/banking/bank-accounts`,
        bankAccountDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/banking/bank-accounts/${id}`,
        bankStatements: `${ROOTS.DASHBOARD}/accounting-finance/banking/bank-statements`,
        bankStatementDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/banking/bank-statements/${id}`,
        reconciliation: `${ROOTS.DASHBOARD}/accounting-finance/banking/reconciliation`,
        reconciliationDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/banking/reconciliation/${id}`,
        transfers: `${ROOTS.DASHBOARD}/accounting-finance/banking/transfers`,
        transferDetail: (id) => `${ROOTS.DASHBOARD}/accounting-finance/banking/transfers/${id}`,
        checkManagement: `${ROOTS.DASHBOARD}/accounting-finance/banking/check-management`,
        checkDetail: (id) => `${ROOTS.DASHBOARD}/accounting-finance/banking/check-management/${id}`,
      },
      // Receivables
      receivables: {
        root: `${ROOTS.DASHBOARD}/accounting-finance/receivables`,
        customerLedger: `${ROOTS.DASHBOARD}/accounting-finance/receivables/customer-ledger`,
        customerLedgerDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/receivables/customer-ledger/${id}`,
        dueInvoices: `${ROOTS.DASHBOARD}/accounting-finance/receivables/due-invoices`,
        dueInvoiceDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/receivables/due-invoices/${id}`,
        agingReport: `${ROOTS.DASHBOARD}/accounting-finance/receivables/aging-report`,
        agingBucketDetail: (bucket) =>
          `${ROOTS.DASHBOARD}/accounting-finance/receivables/aging-report/${bucket}`,
        collectionFollowUp: `${ROOTS.DASHBOARD}/accounting-finance/receivables/collection-follow-up`,
        collectionFollowUpDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/receivables/collection-follow-up/${id}`,
        customerStatements: `${ROOTS.DASHBOARD}/accounting-finance/receivables/customer-statements`,
        customerStatementDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/receivables/customer-statements/${id}`,
      },
      // Payables
      payables: {
        root: `${ROOTS.DASHBOARD}/accounting-finance/payables`,
        supplierLedger: `${ROOTS.DASHBOARD}/accounting-finance/payables/supplier-ledger`,
        supplierLedgerDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/payables/supplier-ledger/${id}`,
        unpaidBills: `${ROOTS.DASHBOARD}/accounting-finance/payables/unpaid-bills`,
        unpaidBillDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/payables/unpaid-bills/${id}`,
        agingReport: `${ROOTS.DASHBOARD}/accounting-finance/payables/aging-report`,
        agingBucketDetail: (bucket) =>
          `${ROOTS.DASHBOARD}/accounting-finance/payables/aging-report/${bucket}`,
        paymentSchedule: `${ROOTS.DASHBOARD}/accounting-finance/payables/payment-schedule`,
        paymentScheduleDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/payables/payment-schedule/${id}`,
        supplierStatements: `${ROOTS.DASHBOARD}/accounting-finance/payables/supplier-statements`,
        supplierStatementDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/payables/supplier-statements/${id}`,
        moneyReceipt: {
          root: `${ROOTS.DASHBOARD}/accounting-finance/payables/money-receipt`,
          create: `${ROOTS.DASHBOARD}/accounting-finance/payables/money-receipt/create`,
          detail: (id) => `${ROOTS.DASHBOARD}/accounting-finance/payables/money-receipt/${id}`,
        },
      },
      // Assets
      assets: {
        root: `${ROOTS.DASHBOARD}/accounting-finance/assets`,
        register: `${ROOTS.DASHBOARD}/accounting-finance/assets/register`,
        acquisition: `${ROOTS.DASHBOARD}/accounting-finance/assets/acquisition`,
        depreciation: `${ROOTS.DASHBOARD}/accounting-finance/assets/depreciation`,
        disposal: `${ROOTS.DASHBOARD}/accounting-finance/assets/disposal`,
        reports: `${ROOTS.DASHBOARD}/accounting-finance/assets/reports`,
      },
      // Budgets
      budgets: {
        root: `${ROOTS.DASHBOARD}/accounting-finance/budgets`,
        plans: `${ROOTS.DASHBOARD}/accounting-finance/budgets/plans`,
        planDetail: (id) => `${ROOTS.DASHBOARD}/accounting-finance/budgets/plans/${id}`,
        lines: `${ROOTS.DASHBOARD}/accounting-finance/budgets/lines`,
        vsActual: `${ROOTS.DASHBOARD}/accounting-finance/budgets/vs-actual`,
        tracking: `${ROOTS.DASHBOARD}/accounting-finance/budgets/tracking`,
        trackingDetail: (id) => `${ROOTS.DASHBOARD}/accounting-finance/budgets/tracking/${id}`,
      },
      // Reports
      reports: {
        root: `${ROOTS.DASHBOARD}/accounting-finance/reports`,
        trialBalance: `${ROOTS.DASHBOARD}/accounting-finance/reports/trial-balance`,
        balanceSheet: `${ROOTS.DASHBOARD}/accounting-finance/reports/balance-sheet`,
        profitLoss: `${ROOTS.DASHBOARD}/accounting-finance/reports/profit-loss`,
        cashFlow: `${ROOTS.DASHBOARD}/accounting-finance/reports/cash-flow`,
        generalLedger: `${ROOTS.DASHBOARD}/accounting-finance/reports/general-ledger`,
        journalReport: `${ROOTS.DASHBOARD}/accounting-finance/reports/journal-report`,
        journalReportEntryDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/reports/journal-report/${id}`,
        accountLedger: `${ROOTS.DASHBOARD}/accounting-finance/reports/account-ledger`,
        customerLedger: `${ROOTS.DASHBOARD}/accounting-finance/reports/customer-ledger`,
        supplierLedger: `${ROOTS.DASHBOARD}/accounting-finance/reports/supplier-ledger`,
        taxReport: `${ROOTS.DASHBOARD}/accounting-finance/reports/tax-report`,
        expenseReport: `${ROOTS.DASHBOARD}/accounting-finance/reports/expense-report`,
        costCenterReport: `${ROOTS.DASHBOARD}/accounting-finance/reports/cost-center-report`,
        assetReport: `${ROOTS.DASHBOARD}/accounting-finance/reports/asset-report`,
        budgetReport: `${ROOTS.DASHBOARD}/accounting-finance/reports/budget-report`,
        executiveSummary: `${ROOTS.DASHBOARD}/accounting-finance/reports/executive-summary`,
        analyticReport: `${ROOTS.DASHBOARD}/accounting-finance/reports/analytic-report`,
        partnerLedger: `${ROOTS.DASHBOARD}/accounting-finance/reports/partner-ledger`,
        taxAudit: `${ROOTS.DASHBOARD}/accounting-finance/reports/tax-audit`,
        consolidatedReport: `${ROOTS.DASHBOARD}/accounting-finance/reports/consolidated-report`,
      },
      // Analytic Accounting
      analyticAccounting: {
        root: `${ROOTS.DASHBOARD}/accounting-finance/analytic-accounting`,
        analyticAccounts: `${ROOTS.DASHBOARD}/accounting-finance/analytic-accounting/analytic-accounts`,
        analyticPlans: `${ROOTS.DASHBOARD}/accounting-finance/analytic-accounting/analytic-plans`,
        analyticPlanDetail: (id) =>
          `${ROOTS.DASHBOARD}/accounting-finance/analytic-accounting/analytic-plans/${id}`,
        analyticItems: `${ROOTS.DASHBOARD}/accounting-finance/analytic-accounting/analytic-items`,
      },
      // Year-End
      yearEnd: {
        root: `${ROOTS.DASHBOARD}/accounting-finance/year-end`,
        yearEndClosing: `${ROOTS.DASHBOARD}/accounting-finance/year-end/year-end-closing`,
        periodLock: `${ROOTS.DASHBOARD}/accounting-finance/year-end/period-lock`,
        openingEntries: `${ROOTS.DASHBOARD}/accounting-finance/year-end/opening-entries`,
      },
      // Settings
      settings: {
        root: `${ROOTS.DASHBOARD}/accounting-finance/settings`,
        postingRules: `${ROOTS.DASHBOARD}/accounting-finance/settings/posting-rules`,
        integrationRules: `${ROOTS.DASHBOARD}/accounting-finance/settings/integration-rules`,
        approvalWorkflow: `${ROOTS.DASHBOARD}/accounting-finance/settings/approval-workflow`,
        numberSeries: `${ROOTS.DASHBOARD}/accounting-finance/settings/number-series`,
        rolePermissions: `${ROOTS.DASHBOARD}/accounting-finance/settings/role-permissions`,
        auditLog: `${ROOTS.DASHBOARD}/accounting-finance/settings/audit-log`,
        currencyRates: `${ROOTS.DASHBOARD}/accounting-finance/settings/currency-rates`,
      },
      // Provident Fund
      providentFund: {
        root: `${ROOTS.DASHBOARD}/accounting-finance/provident-fund`,
        list: `${ROOTS.DASHBOARD}/accounting-finance/provident-fund`,
        create: `${ROOTS.DASHBOARD}/accounting-finance/provident-fund/create`,
        detail: (id) => `${ROOTS.DASHBOARD}/accounting-finance/provident-fund/${id}`,
        edit: (id) => `${ROOTS.DASHBOARD}/accounting-finance/provident-fund/create?editId=${id}`,
      },
    },
    crm: {
      root: `${ROOTS.DASHBOARD}/crm`,
      leads: {
        root: `${ROOTS.DASHBOARD}/crm/leads`,
        list: `${ROOTS.DASHBOARD}/crm/leads`,
        create: `${ROOTS.DASHBOARD}/crm/leads/create`,
        detail: (id) => `${ROOTS.DASHBOARD}/crm/leads/${id}`,
        edit: (id) => `${ROOTS.DASHBOARD}/crm/leads/${id}/edit`,
      },
      movementManagement: {
        root: `${ROOTS.DASHBOARD}/movement-management`,
        list: `${ROOTS.DASHBOARD}/movement-management`,
        create: `${ROOTS.DASHBOARD}/movement-management/create`,
        detail: (id) => `${ROOTS.DASHBOARD}/movement-management/${id}`,
        edit: (id) => `${ROOTS.DASHBOARD}/movement-management/create?editId=${id}`,
      },
    },
    meetingManagement: {
      root: `${ROOTS.DASHBOARD}/meeting-management`,
      list: `${ROOTS.DASHBOARD}/meeting-management/list`,
      create: `${ROOTS.DASHBOARD}/meeting-management/create`,
      calendar: `${ROOTS.DASHBOARD}/meeting-management/calendar`,
      detail: (id) => `${ROOTS.DASHBOARD}/meeting-management/${id}`,
      edit: (id) => `${ROOTS.DASHBOARD}/meeting-management/${id}/edit`,
    },
    formAutomation: {
      root: `${ROOTS.DASHBOARD}/form-automation`,
      form_builder: `${ROOTS.DASHBOARD}/form-automation/form-builder`,
      form_submissions: `${ROOTS.DASHBOARD}/form-automation/form-submissions`,
      approval_workflow: `${ROOTS.DASHBOARD}/form-automation/approval-workflow`,
      form_analytics: `${ROOTS.DASHBOARD}/form-automation/form-analytics`,
    },
    user: {
      root: `${ROOTS.DASHBOARD}/user`,
      list: `${ROOTS.DASHBOARD}/user/list`,
      create: `${ROOTS.DASHBOARD}/user/create`,
      account: `${ROOTS.DASHBOARD}/user/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/user/${id}/edit`,
    },
    settings: {
      root: `${ROOTS.DASHBOARD}/settings`,
      permissions: `${ROOTS.DASHBOARD}/settings/permissions`,
      department: `${ROOTS.DASHBOARD}/settings/department`,
      designation: `${ROOTS.DASHBOARD}/settings/designation`,
      branch: `${ROOTS.DASHBOARD}/settings/branch`,
      grade: `${ROOTS.DASHBOARD}/settings/grade`,
      shift: `${ROOTS.DASHBOARD}/settings/shift`,
      role: `${ROOTS.DASHBOARD}/settings/role`,
      preapprovedip: `${ROOTS.DASHBOARD}/settings/pre-approved-ip`,
      cutOffDate: `${ROOTS.DASHBOARD}/settings/cut-off-date`,
      supervisorLevel: `${ROOTS.DASHBOARD}/settings/supervisor-level`,
      leave: {
        root: `${ROOTS.DASHBOARD}/settings/leave`,
        policy: `${ROOTS.DASHBOARD}/settings/leave/policy`,
        group: `${ROOTS.DASHBOARD}/settings/leave/group`,
        reset: `${ROOTS.DASHBOARD}/settings/leave/reset-period`,
        special: `${ROOTS.DASHBOARD}/settings/leave/special-leave-policies`,
      },
      modulePermissions: `${ROOTS.DASHBOARD}/module-permissions`,
      permissionGroups: `${ROOTS.DASHBOARD}/settings/permission-groups`,
    },
    attendance: {
      root: `${ROOTS.DASHBOARD}/attendance`,
      list: `${ROOTS.DASHBOARD}/attendance/list`,
      webLogin: `${ROOTS.DASHBOARD}/attendance/web-login`,
      adjustment: `${ROOTS.DASHBOARD}/attendance/adjustment`,
      approval: `${ROOTS.DASHBOARD}/attendance/approval`,
      daily: `${ROOTS.DASHBOARD}/attendance/daily`,
      monthly: `${ROOTS.DASHBOARD}/attendance/monthly`,
    },
    holiday: {
      root: `${ROOTS.DASHBOARD}/holiday`,
      list: `${ROOTS.DASHBOARD}/holiday/list`,
      calendar: `${ROOTS.DASHBOARD}/holiday/calendar`,
    },
    leave: {
      root: `${ROOTS.DASHBOARD}/leave`,
      request: `${ROOTS.DASHBOARD}/leave/request`,
      requestDetail: (id) => `${ROOTS.DASHBOARD}/leave/request/${id}`,
      approval: `${ROOTS.DASHBOARD}/leave/approval`,
      calendar: `${ROOTS.DASHBOARD}/leave/calendar`,
      balance: `${ROOTS.DASHBOARD}/leave/balance`,
    },
    payroll: {
      root: `${ROOTS.DASHBOARD}/payroll`,
      generate: `${ROOTS.DASHBOARD}/payroll/generate`,
      list: `${ROOTS.DASHBOARD}/payroll/list`,
      details: (id) => `${ROOTS.DASHBOARD}/payroll/${id}`,
    },
    todo: {
      root: `${ROOTS.DASHBOARD}/todo`,
      list: `${ROOTS.DASHBOARD}/todo/list`,
      create: `${ROOTS.DASHBOARD}/todo/create`,
      edit: (id) => `${ROOTS.DASHBOARD}/todo/${id}/edit`,
      details: (id) => `${ROOTS.DASHBOARD}/todo/details/${id}`,
    },
    projectManagements: {
      root: `${ROOTS.DASHBOARD}/project-managements`,
      dashboard: `${ROOTS.DASHBOARD}/project-managements/dashboard`,
      projects: {
        root: `${ROOTS.DASHBOARD}/project-managements/projects`,
        allProjects: `${ROOTS.DASHBOARD}/project-managements/projects/all-projects`,
        create: `${ROOTS.DASHBOARD}/project-managements/projects/new`,
        detail: (id) => `${ROOTS.DASHBOARD}/project-managements/projects/${id}`,
        edit: (id) => `${ROOTS.DASHBOARD}/project-managements/projects/${id}/edit`,
        report: `${ROOTS.DASHBOARD}/project-managements/projects/report`,
      },
      taskManagement: {
        root: `${ROOTS.DASHBOARD}/project-managements/task-management`,
        allTasks: `${ROOTS.DASHBOARD}/project-managements/task-management/all-tasks`,
        detail: (projectId, taskId) =>
          `${ROOTS.DASHBOARD}/project-managements/task-management/all-tasks/${projectId}/${taskId}`,
        assignment: (projectId, taskId) =>
          `${ROOTS.DASHBOARD}/project-managements/task-management/assignments/${projectId}/${taskId}`,
      },
      expenses: {
        root: `${ROOTS.DASHBOARD}/project-managements/expenses`,
        create: `${ROOTS.DASHBOARD}/project-managements/expenses/create`,
        detail: (id) => `${ROOTS.DASHBOARD}/project-managements/expenses/${id}`,
        advances: {
          root: `${ROOTS.DASHBOARD}/project-managements/expenses/advances`,
          create: `${ROOTS.DASHBOARD}/project-managements/expenses/advances/create`,
          detail: (id) => `${ROOTS.DASHBOARD}/project-managements/expenses/advances/${id}`,
          edit: (id) => `${ROOTS.DASHBOARD}/project-managements/expenses/advances/${id}/edit`,
        },
      },
    },
    ledarsManagement: {
      templates: `${ROOTS.DASHBOARD}/ledars-management/templates`,
    },
    finalSettlement: {
      root: `${ROOTS.DASHBOARD}/final-settlement`,
      list: `${ROOTS.DASHBOARD}/final-settlement`,
      create: `${ROOTS.DASHBOARD}/final-settlement/create`,
      detail: (id) => `${ROOTS.DASHBOARD}/final-settlement/${id}`,
      edit: (id) => `${ROOTS.DASHBOARD}/final-settlement/create?editId=${id}`,
    },
    advances: {
      root: `${ROOTS.DASHBOARD}/project-managements/expenses/advances`,
      create: `${ROOTS.DASHBOARD}/project-managements/expenses/advances/create`,
      detail: (id) => `${ROOTS.DASHBOARD}/project-managements/expenses/advances/${id}`,
      edit: (id) => `${ROOTS.DASHBOARD}/project-managements/expenses/advances/${id}/edit`,
    },
  },
  moneyReceipt: {
    root: '/dashboard/accounting-finance/payables/money-receipt',
    create: '/dashboard/accounting-finance/payables/money-receipt/create',
    detail: (id) => `/dashboard/accounting-finance/payables/money-receipt/${id}`,
  },
};

paths.dashboard.procurement_new = paths.dashboard.procurement;
