'use client';

import { useState } from 'react';
import {
  Info,
  Search,
  XCircle,
  Activity,
  Download,
  CheckCircle,
  AlertTriangle,
} from 'lucide-react';

import { Badge } from '../../components/ui/badge';
import { Button } from '../../components/ui/button';
import { StatCard } from '../../components/stat-card';
import { Card, CardBody } from '../../components/ui/card';
const mockLogs = [
  {
    id: 'LOG-001',
    timestamp: '2026-04-05 14:32:15',
    level: 'error',
    module: 'Payment Processing',
    message: 'Bank API connection timeout — retry 3/3 failed',
    user: 'System',
    ip: '10.0.1.50',
  },
  {
    id: 'LOG-002',
    timestamp: '2026-04-05 14:30:02',
    level: 'warning',
    module: 'Authentication',
    message: 'Failed login attempt for user procurement@aab.org (3rd attempt)',
    user: 'System',
    ip: '103.45.67.89',
  },
  {
    id: 'LOG-003',
    timestamp: '2026-04-05 14:28:45',
    level: 'info',
    module: 'Purchase Order',
    message: 'PO-2026-0039 created by Nazmul Haque',
    user: 'Nazmul Haque',
    ip: '10.0.2.15',
  },
  {
    id: 'LOG-004',
    timestamp: '2026-04-05 14:25:10',
    level: 'info',
    module: 'Material Requisition',
    message: 'MR-2026-0143 approved by Amer Hamid',
    user: 'Amer Hamid',
    ip: '10.0.1.22',
  },
  {
    id: 'LOG-005',
    timestamp: '2026-04-05 14:20:00',
    level: 'warning',
    module: 'Inventory',
    message: 'Low stock alert: Tarpaulins at Ukhiya (qty: 15, threshold: 25)',
    user: 'System',
    ip: '10.0.1.50',
  },
  {
    id: 'LOG-006',
    timestamp: '2026-04-05 14:15:33',
    level: 'info',
    module: 'Vendor Management',
    message: 'Vendor ENL-2026-018 application submitted',
    user: 'External',
    ip: '103.12.34.56',
  },
  {
    id: 'LOG-007',
    timestamp: '2026-04-05 14:10:22',
    level: 'success',
    module: 'Backup',
    message: 'Scheduled daily backup completed — 2.4GB',
    user: 'System',
    ip: '10.0.1.50',
  },
  {
    id: 'LOG-008',
    timestamp: '2026-04-05 14:05:18',
    level: 'error',
    module: 'Email Service',
    message: 'SMTP connection refused — notification queue backed up (42 pending)',
    user: 'System',
    ip: '10.0.1.50',
  },
  {
    id: 'LOG-009',
    timestamp: '2026-04-05 14:00:00',
    level: 'info',
    module: 'Scheduler',
    message: 'Escalation check completed — 3 new escalations triggered',
    user: 'System',
    ip: '10.0.1.50',
  },
  {
    id: 'LOG-010',
    timestamp: '2026-04-05 13:55:44',
    level: 'info',
    module: 'Report',
    message: 'Monthly procurement report generated by Shahana Begum',
    user: 'Shahana Begum',
    ip: '10.0.1.30',
  },
];
const levelMap = {
  error: { variant: 'danger', icon: XCircle },
  warning: { variant: 'warning', icon: AlertTriangle },
  info: { variant: 'info', icon: Info },
  success: { variant: 'success', icon: CheckCircle },
};
export function SystemLogs() {
  const [levelFilter, setLevelFilter] = useState('all');
  const [moduleFilter, setModuleFilter] = useState('all');
  const modules = [...new Set(mockLogs.map((l) => l.module))];
  const filtered = mockLogs.filter((l) => {
    const matchesLevel = levelFilter === 'all' || l.level === levelFilter;
    const matchesModule = moduleFilter === 'all' || l.module === moduleFilter;
    return matchesLevel && matchesModule;
  });
  return (
    <div className="p-8">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-semibold text-foreground mb-2">System Logs</h1>
          <p className="text-muted-foreground">Monitor system events, errors, and activity</p>
        </div>
        <Button variant="outline">
          <Download className="w-4 h-4 mr-2" />
          Export Logs
        </Button>
      </div>

      <div className="grid grid-cols-4 gap-6 mb-6">
        <StatCard title="Total Events (24h)" value={mockLogs.length} icon={Activity} color="blue" />
        <StatCard
          title="Errors"
          value={mockLogs.filter((l) => l.level === 'error').length}
          icon={XCircle}
          color="red"
        />
        <StatCard
          title="Warnings"
          value={mockLogs.filter((l) => l.level === 'warning').length}
          icon={AlertTriangle}
          color="orange"
        />
        <StatCard title="System Health" value="98.5%" icon={CheckCircle} color="green" />
      </div>

      <Card className="mb-6">
        <CardBody>
          <div className="flex gap-4">
            <div className="flex-1 relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <input
                type="text"
                placeholder="Search logs..."
                className="w-full pl-10 pr-4 py-2 border border-input rounded-lg focus:outline-none focus:ring-2 focus:ring-primary"
              />
            </div>
            <select
              value={levelFilter}
              onChange={(e) => setLevelFilter(e.target.value)}
              className="px-4 py-2 border border-input rounded-lg focus:outline-none focus:ring-2 focus:ring-primary"
            >
              <option value="all">All Levels</option>
              <option value="error">Error</option>
              <option value="warning">Warning</option>
              <option value="info">Info</option>
              <option value="success">Success</option>
            </select>
            <select
              value={moduleFilter}
              onChange={(e) => setModuleFilter(e.target.value)}
              className="px-4 py-2 border border-input rounded-lg focus:outline-none focus:ring-2 focus:ring-primary"
            >
              <option value="all">All Modules</option>
              {modules.map((m) => (
                <option key={m} value={m}>
                  {m}
                </option>
              ))}
            </select>
          </div>
        </CardBody>
      </Card>

      <Card>
        <CardBody>
          <div className="space-y-1">
            {filtered.map((log) => {
              const lvl = levelMap[log.level] || levelMap.info;
              const Icon = lvl.icon;
              return (
                <div
                  key={log.id}
                  className="flex items-start gap-3 p-3 rounded-lg hover:bg-secondary/30 transition-colors font-mono text-xs"
                >
                  <Icon
                    className={`w-4 h-4 mt-0.5 flex-shrink-0 ${log.level === 'error' ? 'text-destructive' : log.level === 'warning' ? 'text-warning' : log.level === 'success' ? 'text-green-600' : 'text-blue-600'}`}
                  />
                  <span className="text-muted-foreground w-36 flex-shrink-0">{log.timestamp}</span>
                  <Badge
                    variant={lvl.variant}
                    size="sm"
                    className="w-16 justify-center flex-shrink-0"
                  >
                    {log.level.toUpperCase()}
                  </Badge>
                  <span className="text-primary w-40 flex-shrink-0">[{log.module}]</span>
                  <span className="text-foreground flex-1">{log.message}</span>
                  <span className="text-muted-foreground w-24 flex-shrink-0 text-right">
                    {log.user}
                  </span>
                  <span className="text-muted-foreground w-28 flex-shrink-0 text-right">
                    {log.ip}
                  </span>
                </div>
              );
            })}
          </div>
        </CardBody>
      </Card>
    </div>
  );
}
