export const STATUS_CONFIG = {
  draft: { label: 'Draft', color: 'default' },
  submitted: { label: 'Submitted', color: 'info' },
  under_review: { label: 'Under Review', color: 'warning' },
  approved: { label: 'Approved', color: 'success' },
  rejected: { label: 'Rejected', color: 'error' },
};

export const SIGN_ROLES = {
  supervisor: 'Supervisor',
  upper_authority: 'Upper Authority (Branch/Project/Divisional Head)',
  accounts_officer: 'Accounts Officer',
  trust_member_1: 'PF Trust Board Member 1',
  trust_member_2: 'PF Trust Board Member 2',
  recommender: 'Recommender',
  recorder: 'Recorder',
  approver: 'Approver',
};

export const defaultFormValues = {
  application_date: '',
  applicant_name: '',
  designation: '',
  joining_date: '',
  permanent_date: '',
  monthly_installment_count: '',
  monthly_total_salary: '',
  current_workplace: '',
  program_name: '',
  expected_loan_amount: '',
  loan_purpose: '',
  applicant_signature_date: '',
  supervisor_recommendation: '',
  supervisor_name: '',
  supervisor_designation: '',
  upper_authority_recommendation: '',
  upper_authority_name: '',
  upper_authority_designation: '',
  pf_total_balance: '',
  own_contribution: '',
  org_contribution: '',
  max_loan_eligible: '',
  monthly_interest_principal: '',
  interest_rate_percent: '',
  installment_count: '',
  repayment_months: '',
  accounts_officer_name: '',
  accounts_officer_designation: '',
  trust_member_1_name: '',
  trust_member_2_name: '',
  secretary_approved_amount: '',
};
