'use client';

import Link from 'next/link';
import { useRef, useEffect } from 'react';
import { useParams } from 'next/navigation';
import { Printer, Download, ArrowLeft } from 'lucide-react';

import { paths } from 'src/routes/paths';

import { endpoints } from 'src/utils/axios';

import { useGetRequest } from 'src/actions/ledars-hook';

import { Button } from '../../components/ui/button';
function formatBDT(amount) {
  if (amount >= 10000000) return `\u09F3${(amount / 10000000).toFixed(2)} Cr`;
  if (amount >= 100000) return `\u09F3${(amount / 100000).toFixed(2)} Lakh`;
  return `\u09F3${amount.toLocaleString('en-IN')}`;
}
const mockPrintData = {
  organizationInfo: {
    name: 'Ledars NGO',
    nameBn: '\u09AC\u09BE\u0982\u09B2\u09BE\u09A6\u09C7\u09B6',
    address: 'House 8, Road 136, Gulshan-1, Dhaka-1212, Bangladesh',
    phone: '+880-2-9861120-25',
    email: 'info@actionaid.org',
    website: 'www.actionaid.org/bangladesh',
    logo: '/logo-aab.png',
  },
  cs: {
    id: 'CS-2026-001',
    rfqNumber: 'RFQ-2026-015',
    title: 'IT Equipment & Computer Hardware for Dhaka Head Office',
    category: 'IT Equipment',
    budgetCode: 'BD-ICT-2026-01',
    project: 'Digital Infrastructure Upgrade',
    office: 'Dhaka Head Office',
    createdBy: 'Fatema Khatun',
    createdDate: '2026-03-20',
    autoGenerated: true,
  },
  items: [
    { id: 1, name: 'Desktop Computer (Core i7, 16GB RAM, 512GB SSD)', unit: 'Pcs', qty: 20 },
    { id: 2, name: 'Laptop (Core i5, 8GB RAM, 256GB SSD)', unit: 'Pcs', qty: 10 },
    { id: 3, name: 'Laser Printer (Network, Duplex)', unit: 'Pcs', qty: 5 },
    { id: 4, name: 'UPS (1000VA Online)', unit: 'Pcs', qty: 25 },
    { id: 5, name: 'Network Switch (24-Port Managed)', unit: 'Pcs', qty: 4 },
  ],
  vendors: [
    {
      name: 'TechBD Solutions Ltd',
      location: 'Mohakhali, Dhaka',
      tin: '123456789012',
      recommended: true,
      technicalScore: 88,
      items: [
        { itemId: 1, unitPrice: 62000, totalPrice: 1240000 },
        { itemId: 2, unitPrice: 55000, totalPrice: 550000 },
        { itemId: 3, unitPrice: 28000, totalPrice: 140000 },
        { itemId: 4, unitPrice: 8500, totalPrice: 212500 },
        { itemId: 5, unitPrice: 22000, totalPrice: 88000 },
      ],
      subtotal: 2230500,
      vat: 334575,
      ait: 78068,
      delivery: 15000,
      grandTotal: 2658143,
    },
    {
      name: 'Star Electronics BD',
      location: 'Elephant Road, Dhaka',
      tin: '234567890123',
      recommended: false,
      technicalScore: 76,
      items: [
        { itemId: 1, unitPrice: 58000, totalPrice: 1160000 },
        { itemId: 2, unitPrice: 52000, totalPrice: 520000 },
        { itemId: 3, unitPrice: 25000, totalPrice: 125000 },
        { itemId: 4, unitPrice: 7800, totalPrice: 195000 },
        { itemId: 5, unitPrice: 20000, totalPrice: 80000 },
      ],
      subtotal: 2080000,
      vat: 312000,
      ait: 72800,
      delivery: 12000,
      grandTotal: 2476800,
    },
    {
      name: 'Greenfield IT Solutions',
      location: 'Banani, Dhaka',
      tin: '345678901234',
      recommended: false,
      technicalScore: 82,
      items: [
        { itemId: 1, unitPrice: 64000, totalPrice: 1280000 },
        { itemId: 2, unitPrice: 56000, totalPrice: 560000 },
        { itemId: 3, unitPrice: 30000, totalPrice: 150000 },
        { itemId: 4, unitPrice: 9000, totalPrice: 225000 },
        { itemId: 5, unitPrice: 24000, totalPrice: 96000 },
      ],
      subtotal: 2311000,
      vat: 346650,
      ait: 80885,
      delivery: 18000,
      grandTotal: 2756535,
    },
    {
      name: 'DataCom Technologies Ltd',
      location: 'Gulshan, Dhaka',
      tin: '456789012345',
      recommended: false,
      technicalScore: 71,
      items: [
        { itemId: 1, unitPrice: 59000, totalPrice: 1180000 },
        { itemId: 2, unitPrice: 51000, totalPrice: 510000 },
        { itemId: 3, unitPrice: 26000, totalPrice: 130000 },
        { itemId: 4, unitPrice: 8000, totalPrice: 200000 },
        { itemId: 5, unitPrice: 21000, totalPrice: 84000 },
      ],
      subtotal: 2104000,
      vat: 315600,
      ait: 73640,
      delivery: 14000,
      grandTotal: 2507240,
    },
    {
      name: 'Navana Computing',
      location: 'Motijheel, Dhaka',
      tin: '567890123456',
      recommended: false,
      technicalScore: 84,
      items: [
        { itemId: 1, unitPrice: 63000, totalPrice: 1260000 },
        { itemId: 2, unitPrice: 54000, totalPrice: 540000 },
        { itemId: 3, unitPrice: 29000, totalPrice: 145000 },
        { itemId: 4, unitPrice: 8800, totalPrice: 220000 },
        { itemId: 5, unitPrice: 23000, totalPrice: 92000 },
      ],
      subtotal: 2257000,
      vat: 338550,
      ait: 78995,
      delivery: 16000,
      grandTotal: 2690545,
    },
  ],
  recommendation: {
    vendor: 'TechBD Solutions Ltd',
    summary:
      'TechBD Solutions Ltd is recommended based on highest combined technical-financial evaluation score. Superior technical compliance (88/100), OEM-authorized warranty, fastest delivery (15 working days), and proven track record with 8 successful orders for Ledars NGO.',
  },
  approvalTrail: [
    {
      level: 1,
      role: 'Procurement/Admin Manager',
      name: 'Md. Kamal Hossain',
      designation: 'Manager, Procurement & Administration',
      date: '2026-03-21',
      status: 'Approved',
    },
    {
      level: 2,
      role: 'Procurement Committee',
      name: 'Committee (4 members)',
      designation: 'As per Authority Matrix',
      date: 'Pending',
      status: 'Pending',
    },
    {
      level: 3,
      role: 'Final Approver (Authority Matrix)',
      name: 'Farah Kabir',
      designation: 'Country Director',
      date: '',
      status: 'Awaiting',
    },
  ],
};
export function ComparativeStatementPrint() {
  const { id } = useParams();
  const { data: cs, loading } = useGetRequest(
    id ? endpoints.procurement_management.comparative_statement_by_id(id) : null
  );

  if (loading)
    return (
      <div className="print:hidden p-8 text-center text-sm text-muted-foreground">Loading...</div>
    );
  if (!cs)
    return (
      <div className="print:hidden p-8 text-center text-sm text-muted-foreground">
        CS not found.
      </div>
    );

  const { organizationInfo } = mockPrintData;
  const items = cs?.items ?? [];
  const vendors = cs?.vendors ?? [];
  const recommendedVendor = vendors.find((v) => v.is_recommended);
  const approvalTrail = cs?.approval_matrix ?? [];
  const lowestGrandTotal = vendors.length
    ? Math.min(...vendors.map((v) => v.financial_proposal?.grand_total ?? Infinity))
    : 0;
  const handlePrint = () => window.print();

  const hasPrinted = useRef(false);
  useEffect(() => {
    if (!loading && cs && !hasPrinted.current) {
      hasPrinted.current = true;
      const t = setTimeout(() => window.print(), 800);
      return () => clearTimeout(t);
    }
    return undefined;
  }, [loading, cs]);
  return (
    <div>
      {/* Screen-only controls */}
      <div className="print:hidden p-3 bg-muted border-b border-border sticky top-0 z-10">
        <div className="max-w-[210mm] mx-auto flex items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <Link href={paths.dashboard.procurement.comparative.detail(id)}>
              <Button variant="outline" size="sm">
                <ArrowLeft className="w-3.5 h-3.5 mr-1.5" />
                Back to CS
              </Button>
            </Link>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" onClick={handlePrint}>
              <Download className="w-3.5 h-3.5 mr-1.5" />
              Export PDF
            </Button>
            <Button size="sm" onClick={handlePrint}>
              <Printer className="w-3.5 h-3.5 mr-1.5" />
              Print
            </Button>
          </div>
        </div>
      </div>

      {/* Printable A4 Content */}
      <div id="cs-print-area" className="max-w-[210mm] mx-auto bg-white print:max-w-none">
        <div className="p-8 print:p-6">
          {/* AAB Organization Header */}
          <div className="text-center border-b-2 border-gray-800 pb-4 mb-6">
            <h1 className="text-xl font-bold text-gray-900 tracking-wide">Ledars NGO</h1>
            <p className="text-xs text-gray-500 mt-0.5">{organizationInfo.nameBn}</p>
            <p className="text-xs text-gray-600 mt-1">{organizationInfo.address}</p>
            <p className="text-xs text-gray-600">
              Phone: {organizationInfo.phone} | Email: {organizationInfo.email}
            </p>
            <div className="mt-3 inline-block px-6 py-1.5 bg-gray-100 border border-gray-300 rounded">
              <h2 className="text-sm font-bold text-gray-800 uppercase tracking-wider">
                Comparative Statement (CS)
              </h2>
            </div>
          </div>

          {/* CS Reference Info */}
          <div className="grid grid-cols-2 gap-x-8 gap-y-1.5 text-xs mb-6">
            <div className="flex">
              <span className="font-semibold text-gray-700 w-32">CS Number:</span>
              <span className="text-gray-900">{cs?.cs_number}</span>
            </div>
            <div className="flex">
              <span className="font-semibold text-gray-700 w-32">RFQ Reference:</span>
              <span className="text-gray-900">{cs?.rfq_number}</span>
            </div>
            <div className="flex">
              <span className="font-semibold text-gray-700 w-32">Title:</span>
              <span className="text-gray-900">{cs?.rfq_title ?? cs?.title}</span>
            </div>
            <div className="flex">
              <span className="font-semibold text-gray-700 w-32">Category:</span>
              <span className="text-gray-900">{cs?.category}</span>
            </div>
            <div className="flex">
              <span className="font-semibold text-gray-700 w-32">Budget Code:</span>
              <span className="text-gray-900">{cs?.budget_code}</span>
            </div>
            <div className="flex">
              <span className="font-semibold text-gray-700 w-32">Project:</span>
              <span className="text-gray-900">{cs?.project}</span>
            </div>
            <div className="flex">
              <span className="font-semibold text-gray-700 w-32">Requesting Office:</span>
              <span className="text-gray-900">{cs?.office_info?.name}</span>
            </div>
            <div className="flex">
              <span className="font-semibold text-gray-700 w-32">Prepared By:</span>
              <span className="text-gray-900">{cs?.created_by_name ?? cs?.created_by}</span>
            </div>
            <div className="flex">
              <span className="font-semibold text-gray-700 w-32">Date:</span>
              <span className="text-gray-900">
                {cs?.created_at ? new Date(cs.created_at).toLocaleDateString('en-GB') : '\u2014'}
              </span>
            </div>
            <div className="flex">
              <span className="font-semibold text-gray-700 w-32">Generation:</span>
              <span className="text-gray-900">
                {cs?.auto_extracted ? 'Auto-Generated from Financial Proposals' : 'Manual'}
              </span>
            </div>
          </div>

          {/* Vendor Comparison Table */}
          <div className="mb-6">
            <h3 className="text-sm font-bold text-gray-800 mb-2 border-b border-gray-300 pb-1">
              A. Vendor Price Comparison
            </h3>
            <p className="text-[10px] text-gray-500 mb-2">
              All amounts in BDT ({'\u09F3'}). VAT @15% and AIT @3.5% as per NBR regulations.
            </p>
            <div className="overflow-x-auto">
              <table className="w-full text-[10px] border-collapse border border-gray-400">
                <thead>
                  <tr className="bg-gray-100">
                    <th
                      className="border border-gray-400 px-2 py-1.5 text-left font-semibold"
                      rowSpan={2}
                    >
                      SL
                    </th>
                    <th
                      className="border border-gray-400 px-2 py-1.5 text-left font-semibold"
                      rowSpan={2}
                    >
                      Item Name
                    </th>
                    <th
                      className="border border-gray-400 px-1 py-1.5 text-center font-semibold"
                      rowSpan={2}
                    >
                      Unit
                    </th>
                    <th
                      className="border border-gray-400 px-1 py-1.5 text-center font-semibold"
                      rowSpan={2}
                    >
                      Qty
                    </th>
                    {vendors.map((v, i) => (
                      <th
                        key={i}
                        className={`border border-gray-400 px-2 py-1.5 text-center font-semibold ${
                          v.is_recommended ? 'bg-green-50' : ''
                        }`}
                        colSpan={2}
                      >
                        {v.name}
                        {v.is_recommended ? ' *' : ''}
                      </th>
                    ))}
                  </tr>
                  <tr className="bg-gray-50">
                    {vendors.map((v, i) => (
                      <>
                        <th
                          key={`${i}u`}
                          className={`border border-gray-400 px-1 py-1 text-center font-medium text-gray-600 ${
                            v.is_recommended ? 'bg-green-50' : ''
                          }`}
                        >
                          Unit Price
                        </th>
                        <th
                          key={`${i}t`}
                          className={`border border-gray-400 px-1 py-1 text-center font-medium text-gray-600 ${
                            v.is_recommended ? 'bg-green-50' : ''
                          }`}
                        >
                          Total
                        </th>
                      </>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {items.map((item, idx) => (
                    <tr key={item.id}>
                      <td className="border border-gray-400 px-2 py-1 text-center">{idx + 1}</td>
                      <td className="border border-gray-400 px-2 py-1">{item.name}</td>
                      <td className="border border-gray-400 px-1 py-1 text-center">{item.unit}</td>
                      <td className="border border-gray-400 px-1 py-1 text-center">{item.qty}</td>
                      {vendors.map((v, vi) => {
                        const fi = v.financial_proposal?.items?.find((f) => f.item_id === item.id);
                        return (
                          <>
                            <td
                              key={`${vi}u`}
                              className={`border border-gray-400 px-1 py-1 text-right ${
                                v.is_recommended ? 'bg-green-50' : ''
                              }`}
                            >
                              {fi ? fi.unit_price.toLocaleString('en-IN') : '-'}
                            </td>
                            <td
                              key={`${vi}t`}
                              className={`border border-gray-400 px-1 py-1 text-right ${
                                v.is_recommended ? 'bg-green-50' : ''
                              }`}
                            >
                              {fi ? fi.total_price.toLocaleString('en-IN') : '-'}
                            </td>
                          </>
                        );
                      })}
                    </tr>
                  ))}
                  {/* Subtotal */}
                  <tr className="font-semibold bg-gray-50">
                    <td className="border border-gray-400 px-2 py-1" colSpan={4}>
                      Subtotal
                    </td>
                    {vendors.map((v, i) => (
                      <>
                        <td
                          key={`${i}s`}
                          className={`border border-gray-400 px-1 py-1 ${
                            v.is_recommended ? 'bg-green-50' : ''
                          }`}
                        ></td>
                        <td
                          key={`${i}st`}
                          className={`border border-gray-400 px-1 py-1 text-right ${
                            v.is_recommended ? 'bg-green-50' : ''
                          }`}
                        >
                          {(v.financial_proposal?.subtotal ?? 0).toLocaleString('en-IN')}
                        </td>
                      </>
                    ))}
                  </tr>
                  <tr>
                    <td className="border border-gray-400 px-2 py-1" colSpan={4}>
                      VAT (15%)
                    </td>
                    {vendors.map((v, i) => (
                      <>
                        <td
                          key={`${i}v1`}
                          className={`border border-gray-400 px-1 py-1 ${
                            v.is_recommended ? 'bg-green-50' : ''
                          }`}
                        ></td>
                        <td
                          key={`${i}v2`}
                          className={`border border-gray-400 px-1 py-1 text-right ${
                            v.is_recommended ? 'bg-green-50' : ''
                          }`}
                        >
                          {(v.financial_proposal?.vat ?? 0).toLocaleString('en-IN')}
                        </td>
                      </>
                    ))}
                  </tr>
                  <tr>
                    <td className="border border-gray-400 px-2 py-1" colSpan={4}>
                      AIT (3.5%)
                    </td>
                    {vendors.map((v, i) => (
                      <>
                        <td
                          key={`${i}a1`}
                          className={`border border-gray-400 px-1 py-1 ${
                            v.is_recommended ? 'bg-green-50' : ''
                          }`}
                        ></td>
                        <td
                          key={`${i}a2`}
                          className={`border border-gray-400 px-1 py-1 text-right ${
                            v.is_recommended ? 'bg-green-50' : ''
                          }`}
                        >
                          {(v.financial_proposal?.ait ?? 0).toLocaleString('en-IN')}
                        </td>
                      </>
                    ))}
                  </tr>
                  <tr>
                    <td className="border border-gray-400 px-2 py-1" colSpan={4}>
                      Delivery Charge
                    </td>
                    {vendors.map((v, i) => (
                      <>
                        <td
                          key={`${i}d1`}
                          className={`border border-gray-400 px-1 py-1 ${
                            v.is_recommended ? 'bg-green-50' : ''
                          }`}
                        ></td>
                        <td
                          key={`${i}d2`}
                          className={`border border-gray-400 px-1 py-1 text-right ${
                            v.is_recommended ? 'bg-green-50' : ''
                          }`}
                        >
                          {(v.financial_proposal?.delivery ?? 0).toLocaleString('en-IN')}
                        </td>
                      </>
                    ))}
                  </tr>
                  <tr className="font-bold bg-gray-100">
                    <td className="border border-gray-400 px-2 py-1.5" colSpan={4}>
                      Grand Total (BDT)
                    </td>
                    {vendors.map((v, i) => (
                      <>
                        <td
                          key={`${i}g1`}
                          className={`border border-gray-400 px-1 py-1.5 ${
                            v.is_recommended ? 'bg-green-100' : ''
                          }`}
                        ></td>
                        <td
                          key={`${i}g2`}
                          className={`border border-gray-400 px-1 py-1.5 text-right ${
                            v.is_recommended ? 'bg-green-100' : ''
                          }${
                            (v.financial_proposal?.grand_total ?? 0) === lowestGrandTotal
                              ? ' text-green-700'
                              : ''
                          }`}
                        >
                          {'\u09F3'}
                          {(v.financial_proposal?.grand_total ?? 0).toLocaleString('en-IN')}
                          {(v.financial_proposal?.grand_total ?? 0) === lowestGrandTotal && ' (L)'}
                        </td>
                      </>
                    ))}
                  </tr>
                  {/* Technical Score */}
                  <tr className="bg-gray-50 font-semibold">
                    <td className="border border-gray-400 px-2 py-1" colSpan={4}>
                      Technical Score
                    </td>
                    {vendors.map((v, i) => (
                      <>
                        <td
                          key={`${i}ts1`}
                          className={`border border-gray-400 px-1 py-1 ${
                            v.is_recommended ? 'bg-green-50' : ''
                          }`}
                        ></td>
                        <td
                          key={`${i}ts2`}
                          className={`border border-gray-400 px-1 py-1 text-center ${
                            v.is_recommended ? 'bg-green-50 text-green-700' : ''
                          }`}
                        >
                          {v.technical_score ?? 0}/100
                        </td>
                      </>
                    ))}
                  </tr>
                </tbody>
              </table>
            </div>
            <p className="text-[9px] text-gray-500 mt-1">* Recommended vendor | (L) = Lowest bid</p>
          </div>

          {/* Recommendation */}
          <div className="mb-6">
            <h3 className="text-sm font-bold text-gray-800 mb-2 border-b border-gray-300 pb-1">
              B. Recommendation
            </h3>
            <div className="p-3 border border-gray-300 rounded bg-green-50">
              <p className="text-xs font-semibold text-gray-800 mb-1">
                Recommended Vendor: {recommendedVendor?.name ?? '\u2014'}
              </p>
              <p className="text-[10px] text-gray-600 leading-relaxed">
                {cs?.justification ??
                  'Recommended based on combined technical and financial evaluation.'}
              </p>
            </div>
          </div>

          {/* Approval Trail — TOR: 3 levels */}
          <div className="mb-6">
            <h3 className="text-sm font-bold text-gray-800 mb-2 border-b border-gray-300 pb-1">
              C. Approval Trail
            </h3>
            <table className="w-full text-[10px] border-collapse border border-gray-400">
              <thead>
                <tr className="bg-gray-100">
                  <th className="border border-gray-400 px-2 py-1.5 text-left font-semibold w-12">
                    Level
                  </th>
                  <th className="border border-gray-400 px-2 py-1.5 text-left font-semibold">
                    Role
                  </th>
                  <th className="border border-gray-400 px-2 py-1.5 text-left font-semibold">
                    Name &amp; Designation
                  </th>
                  <th className="border border-gray-400 px-2 py-1.5 text-center font-semibold">
                    Date
                  </th>
                  <th className="border border-gray-400 px-2 py-1.5 text-center font-semibold">
                    Status
                  </th>
                  <th className="border border-gray-400 px-2 py-1.5 text-center font-semibold w-28">
                    Signature
                  </th>
                </tr>
              </thead>
              <tbody>
                {approvalTrail.map((a) => (
                  <tr key={a.level}>
                    <td className="border border-gray-400 px-2 py-2 text-center font-semibold">
                      {a.level}
                    </td>
                    <td className="border border-gray-400 px-2 py-2">{a.role}</td>
                    <td className="border border-gray-400 px-2 py-2">
                      {a.name}
                      <br />
                      <span className="text-gray-500">{a.designation ?? '\u2014'}</span>
                    </td>
                    <td className="border border-gray-400 px-2 py-2 text-center">
                      {a.date || '\u2014'}
                    </td>
                    <td className="border border-gray-400 px-2 py-2 text-center">
                      <span
                        className={
                          a.status?.[0]?.toUpperCase() + a.status?.slice(1) === 'Approved'
                            ? 'font-semibold text-green-700'
                            : a.status?.[0]?.toUpperCase() + a.status?.slice(1) === 'Pending'
                              ? 'text-amber-600'
                              : 'text-gray-500'
                        }
                      >
                        {a.status ? a.status[0].toUpperCase() + a.status.slice(1) : '\u2014'}
                      </span>
                    </td>
                    <td className="border border-gray-400 px-2 py-6"></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Footer */}
          <div className="border-t border-gray-300 pt-3 mt-8">
            <div className="flex justify-between text-[9px] text-gray-500">
              <span>Generated by AAB Procurement Automation System</span>
              <span>
                {cs?.cs_number} |{' '}
                {cs?.created_at ? new Date(cs.created_at).toLocaleDateString('en-GB') : '\u2014'}
              </span>
              <span>Ledars NGO &mdash; Confidential</span>
            </div>
            <p className="text-[8px] text-gray-400 text-center mt-1">
              This document is auto-generated. Unauthorized modification is prohibited.
            </p>
          </div>
        </div>
      </div>

      {/* Print styles */}
      <style>
        {`
          @media print {
            /* Hide everything except the CS content */
            body * { visibility: hidden !important; }
            #cs-print-area, #cs-print-area * { visibility: visible !important; }
            #cs-print-area {
              position: fixed !important;
              top: 0 !important;
              left: 0 !important;
              width: 100% !important;
              max-width: none !important;
              margin: 0 !important;
              padding: 0 !important;
              background: white !important;
              z-index: 9999 !important;
            }
            body {
              -webkit-print-color-adjust: exact;
              print-color-adjust: exact;
            }
            @page { size: A4 landscape; margin: 10mm; }
          }
        `}
      </style>
    </div>
  );
}
