'use client';

import { toast } from 'sonner';
import { useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import {
  Zap,
  Bell,
  User,
  XCircle,
  Calendar,
  FileText,
  ArrowLeft,
  RotateCcw,
  AlertCircle,
  CheckCircle,
} from 'lucide-react';

import { paths } from 'src/routes/paths';

import axiosInstance, { endpoints } from 'src/utils/axios';

import { useGetRequest } from 'src/actions/ledars-hook';

import { Badge } from '../../components/ui/badge';
import { Button } from '../../components/ui/button';
import { Card, CardBody, CardHeader } from '../../components/ui/card';
function formatBDT(amount) {
  const n = parseFloat(amount) || 0;
  if (n >= 10000000) return `\u09F3${(n / 10000000).toFixed(2)} Cr`;
  if (n >= 100000) return `\u09F3${(n / 100000).toFixed(2)} Lakh`;
  return `\u09F3${n.toLocaleString('en-IN')}`;
}
const REMOVED_mockWOApprovalData = {
  id: 'WO-AAB-2026-003',
  poNumber: 'PO-AAB-2026-003',
  requisitionNumber: 'MRF-2026-009',
  rfqNumber: 'RFQ-2026-009',
  csNumber: 'CS-2026-005',
  awardNumber: 'AWD-AAB-2026-003',
  title: 'Printing & Publication \u2014 Annual Report FY2025-26',
  category: 'Printing & Publications',
  orderDate: '2026-03-10',
  deliveryDeadline: '2026-04-20',
  submittedBy: 'Tasneem Jahan',
  submittedDate: '2026-03-10 09:30 AM',
  currentApprover: 'Procurement Committee',
  autoGenerated: true,
  sourceCS: 'CS-2026-005',
  budgetCode: 'BD-PUB-2026-01',
  project: 'Communications & Advocacy',
  vendor: {
    name: 'Dhaka Print House Ltd',
    code: 'VEN-BD-005',
    email: 'orders@dhakaprinthouse.com.bd',
    phone: '+880-2-7654321',
    address: 'Fakirapool, Dhaka-1000, Bangladesh',
    tin: '305678901234',
  },
  deliveryLocation: 'Ledars NGO\nHouse 8, Road 136, Gulshan-1\nDhaka-1212, Bangladesh',
  paymentTerms: '30 days after GRN & invoice verification',
  warrantyPeriod: 'N/A (Printed Materials)',
  notes:
    'Color proofs must be approved before full print run. Delivery in batches: 50% by 10 April, remaining by 20 April. Eco-friendly paper stock preferred. VAT 15% and AIT 3.5% deducted at source.',
  items: [
    {
      id: '1',
      description: 'Annual Report FY2025-26 (English)',
      specification: 'A4, 120 pages, full color, matt lamination cover, 130gsm art paper',
      quantity: 2000,
      unitPrice: 180,
      total: 360000,
    },
    {
      id: '2',
      description: 'Annual Report FY2025-26 (Bangla)',
      specification: 'A4, 92 pages, full color, matt lamination cover, 130gsm art paper',
      quantity: 3000,
      unitPrice: 150,
      total: 450000,
    },
    {
      id: '3',
      description: 'Advocacy Brochure (Trilingual)',
      specification: 'A5, 16 pages, full color, saddle stitch, 150gsm glossy',
      quantity: 5000,
      unitPrice: 35,
      total: 175000,
    },
    {
      id: '4',
      description: 'Programme Poster (A2 Size)',
      specification: 'A2, single side, full color, 200gsm coated',
      quantity: 1000,
      unitPrice: 45,
      total: 45000,
    },
    {
      id: '5',
      description: 'Folder with Pocket',
      specification: 'A4, full color both sides, 300gsm card, matt lamination',
      quantity: 2000,
      unitPrice: 55,
      total: 110000,
    },
    {
      id: '6',
      description: 'Bookmark / Leaflet',
      specification: 'Custom size, full color, 250gsm art card, UV coating',
      quantity: 10000,
      unitPrice: 6,
      total: 60000,
    },
  ],
  totalAmount: 1200000,
  approvalChain: [
    {
      role: 'Procurement/Admin Manager',
      name: 'Md. Kamal Hossain',
      status: 'approved',
      date: '2026-03-10 11:00 AM',
      comments: 'Budget confirmed under BD-PUB-2026-01. Vendor has strong track record.',
    },
    {
      role: 'Procurement Committee',
      name: 'Committee Review',
      status: 'pending',
      date: null,
      comments: null,
      members: [
        { name: 'Shahana Begum', role: 'Programme Director', status: 'approved' },
        { name: 'Md. Rafiqul Islam', role: 'Finance Manager', status: 'pending' },
        { name: 'Dr. Nafisa Akter', role: 'Health Programme Head', status: 'pending' },
      ],
    },
    {
      role: 'Country Director (Final Approver)',
      name: 'Farah Kabir',
      status: 'not-started',
      date: null,
      comments: null,
    },
  ],
};
export function WorkOrderApproval() {
  const router = useRouter();
  const { id } = useParams();
  const [showApproveModal, setShowApproveModal] = useState(false);
  const [showRejectModal, setShowRejectModal] = useState(false);
  const [showReturnModal, setShowReturnModal] = useState(false);
  const [comments, setComments] = useState('');
  const [rejectionReason, setRejectionReason] = useState('');
  const [returnReason, setReturnReason] = useState('');
  const [submitting, setSubmitting] = useState(false);

  const { data: wo, isLoading } = useGetRequest(
    id ? endpoints.procurement_management.work_order_by_id(id) : null
  );
  const deliveryTimelineDays =
    wo?.orderDate && wo?.deliveryDeadline
      ? Math.max(
          0,
          Math.ceil(
            (new Date(wo.deliveryDeadline).getTime() - new Date(wo.orderDate).getTime()) /
              (1000 * 60 * 60 * 24)
          )
        )
      : null;

  const handleApprove = async () => {
    if (!comments.trim()) {
      toast.error('Please add comments for your approval');
      return;
    }
    try {
      setSubmitting(true);
      await axiosInstance.post(endpoints.procurement_management.work_order_approve(id), {
        comments,
      });
      toast.success('Work order approved successfully.');
      router.push(paths.dashboard.procurement.workOrders.list);
    } catch (err) {
      toast.error(err?.response?.data?.detail || 'Approval failed. Please try again.');
    } finally {
      setSubmitting(false);
      setShowApproveModal(false);
    }
  };

  const handleReject = async () => {
    if (!rejectionReason.trim()) {
      toast.error('Please provide a reason for rejection');
      return;
    }
    try {
      setSubmitting(true);
      await axiosInstance.post(endpoints.procurement_management.work_order_reject(id), {
        comments: rejectionReason,
      });
      toast.success('Work order rejected.');
      router.push(paths.dashboard.procurement.workOrders.list);
    } catch (err) {
      toast.error(err?.response?.data?.detail || 'Rejection failed. Please try again.');
    } finally {
      setSubmitting(false);
      setShowRejectModal(false);
    }
  };

  const handleReturn = () => {
    if (!returnReason.trim()) {
      toast.error('Please provide reasons for returning');
      return;
    }
    toast.info('Return for revision is not yet available.');
    setShowReturnModal(false);
  };

  if (isLoading || !wo) {
    return (
      <div className="p-8 text-center text-muted-foreground">
        {isLoading ? 'Loading…' : 'Work order not found.'}
      </div>
    );
  }
  return (
    <div className="p-4 md:p-6 lg:p-8">
      <div className="mb-6">
        <div className="flex items-center gap-4 mb-4">
          <button
            type="button"
            onClick={() => router.push(paths.dashboard.procurement.workOrders.list)}
            className="p-2 hover:bg-muted rounded-lg transition-colors"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div className="flex-1">
            <h1 className="text-2xl font-semibold text-foreground mb-1">Work Order Approval</h1>
            <p className="text-muted-foreground">
              {wo.workOrderNumber || wo.id} &mdash; {wo.title}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <Badge variant="warning">Pending Your Approval</Badge>
          {wo.autoGenerated && (
            <Badge variant="info">
              <Zap className="w-3 h-3 mr-1" />
              Auto-Generated from {wo.csNumber}
            </Badge>
          )}
          <span className="text-sm text-muted-foreground">
            Submitted by {wo.created_by} on{' '}
            {wo.createdAt ? new Date(wo.createdAt).toLocaleString() : ''}
          </span>
        </div>
      </div>

      <Card className="mb-6 border-warning bg-warning/5">
        <CardBody>
          <div className="flex items-start gap-3">
            <AlertCircle className="w-5 h-5 text-warning mt-0.5" />
            <div>
              <p className="font-medium text-foreground mb-1">
                Action Required &mdash; Digital Approval Workflow
              </p>
              <p className="text-sm text-muted-foreground">
                This work order requires your approval. Review all details carefully. Upon approval,
                vendor will be notified via Portal.
              </p>
            </div>
          </div>
        </CardBody>
      </Card>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          {/* Summary */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <Card>
              <CardBody>
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Total Amount</p>
                    <p className="text-xl font-semibold text-foreground">
                      {formatBDT(wo.totalAmount)}
                    </p>
                  </div>
                  <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                    <FileText className="w-3.5 h-3.5 text-primary" />
                  </div>
                </div>
              </CardBody>
            </Card>
            <Card>
              <CardBody>
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Total Items</p>
                    <p className="text-xl font-semibold text-foreground">{wo.items?.length ?? 0}</p>
                  </div>
                  <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                    <FileText className="w-3.5 h-3.5 text-primary" />
                  </div>
                </div>
              </CardBody>
            </Card>
            <Card>
              <CardBody>
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Delivery Timeline</p>
                    <p className="text-lg font-semibold text-foreground">
                      {deliveryTimelineDays !== null ? `${deliveryTimelineDays} days` : '-'}
                    </p>
                  </div>
                  <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                    <Calendar className="w-3.5 h-3.5 text-primary" />
                  </div>
                </div>
              </CardBody>
            </Card>
          </div>

          {/* WO Info */}
          <Card>
            <CardHeader title="Work Order Information" />
            <CardBody>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <p className="text-sm text-muted-foreground mb-1">WO Number</p>
                  <p className="font-medium text-foreground">{wo.workOrderNumber || wo.id}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground mb-1">Award Number</p>
                  <p className="font-medium text-foreground">{wo.awardNumber || '-'}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground mb-1">Source CS</p>
                  <p className="font-medium text-primary">{wo.csNumber || '-'}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground mb-1">MRF Number</p>
                  <p className="font-medium text-primary">{wo.requisitionNumber || '-'}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground mb-1">RFQ Number</p>
                  <p className="font-medium text-primary">{wo.rfqNumber || '-'}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground mb-1">Budget Code</p>
                  <p className="font-medium text-foreground">{wo.budgetCode || '-'}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground mb-1">Order Date</p>
                  <p className="font-medium text-foreground">{wo.orderDate || '-'}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground mb-1">Delivery Deadline</p>
                  <p className="font-medium text-foreground">{wo.deliveryDeadline || '-'}</p>
                </div>
              </div>
            </CardBody>
          </Card>

          {/* Vendor */}
          <Card>
            <CardHeader title="Vendor Information" />
            <CardBody>
              <div className="space-y-3">
                <h3 className="font-semibold text-foreground">{wo.vendor?.name || '-'}</h3>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Email</p>
                    <p className="text-sm font-medium text-foreground">{wo.vendor?.email || '-'}</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Contact Person</p>
                    <p className="text-sm font-medium text-foreground">
                      {wo.vendor?.contactPerson || '-'}
                    </p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Phone</p>
                    <p className="text-sm font-medium text-foreground">{wo.vendor?.phone || '-'}</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Address</p>
                    <p className="text-sm font-medium text-foreground">
                      {wo.vendor?.address || '-'}
                    </p>
                  </div>
                </div>
              </div>
            </CardBody>
          </Card>

          {/* Items */}
          <Card>
            <CardHeader title="Order Items" description="Review all items &mdash; amounts in BDT" />
            <CardBody>
              <div className="border border-border rounded-lg overflow-hidden">
                <table className="w-full">
                  <thead className="bg-muted/50">
                    <tr className="border-b border-border">
                      <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground">
                        Item Name
                      </th>
                      <th className="px-4 py-3 text-right text-xs font-medium text-muted-foreground">
                        Qty
                      </th>
                      <th className="px-4 py-3 text-right text-xs font-medium text-muted-foreground">
                        Unit Price
                      </th>
                      <th className="px-4 py-3 text-right text-xs font-medium text-muted-foreground">
                        Total
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {(wo.items || []).map((item, idx) => (
                      <tr key={item.id ?? idx} className="border-b border-border last:border-0">
                        <td className="px-4 py-3">
                          <p className="text-sm font-medium text-foreground">
                            {item.name || item.description}
                          </p>
                          <p className="text-xs text-muted-foreground mt-1">{item.specification}</p>
                        </td>
                        <td className="px-4 py-3 text-sm text-right text-foreground">
                          {(item.quantity ?? 0).toLocaleString()}
                        </td>
                        <td className="px-4 py-3 text-sm text-right text-foreground">
                          {formatBDT(item.unitPrice)}
                        </td>
                        <td className="px-4 py-3 text-sm text-right font-medium text-foreground">
                          {formatBDT(item.total)}
                        </td>
                      </tr>
                    ))}
                    <tr className="bg-muted/30">
                      <td
                        colSpan={3}
                        className="px-4 py-3 text-sm font-semibold text-foreground text-right"
                      >
                        Grand Total:
                      </td>
                      <td className="px-4 py-3 text-sm font-semibold text-primary text-right">
                        {formatBDT(wo.totalAmount)}
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </CardBody>
          </Card>

          {/* Delivery & Terms */}
          <Card>
            <CardHeader title="Delivery & Payment Terms" />
            <CardBody>
              <div className="space-y-4">
                <div>
                  <p className="text-sm font-medium text-foreground mb-2">Delivery Location</p>
                  <div className="p-3 bg-muted/30 rounded-lg">
                    <p className="text-sm text-foreground whitespace-pre-line">
                      {wo.deliveryLocation}
                    </p>
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <p className="text-sm font-medium text-foreground mb-2">Payment Terms</p>
                    <p className="text-sm text-muted-foreground">{wo.paymentTerms}</p>
                  </div>
                  <div>
                    <p className="text-sm font-medium text-foreground mb-2">Warranty Period</p>
                    <p className="text-sm text-muted-foreground">{wo.warrantyPeriod}</p>
                  </div>
                </div>
                {wo.notes && (
                  <div>
                    <p className="text-sm font-medium text-foreground mb-2">Special Instructions</p>
                    <div className="p-3 bg-muted/30 rounded-lg">
                      <p className="text-sm text-foreground">{wo.notes}</p>
                    </div>
                  </div>
                )}
              </div>
            </CardBody>
          </Card>

          {/* Decision */}
          <Card className="border-primary/20">
            <CardHeader
              title="Your Decision"
              description="Add comments and approve, reject, or return for revision"
            />
            <CardBody>
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">
                    Approval Comments *
                  </label>
                  <textarea
                    value={comments}
                    onChange={(e) => setComments(e.target.value)}
                    placeholder="Enter your comments, observations, or conditions..."
                    rows={4}
                    className="w-full px-3 py-2 border border-input rounded-lg focus:outline-none focus:ring-2 focus:ring-primary resize-none"
                  />
                </div>
                <div className="flex gap-3">
                  <Button
                    variant="success"
                    className="flex-1"
                    onClick={() => setShowApproveModal(true)}
                  >
                    <CheckCircle className="w-3.5 h-3.5 mr-1.5" />
                    Approve
                  </Button>
                  <Button
                    variant="warning"
                    className="flex-1"
                    onClick={() => setShowReturnModal(true)}
                  >
                    <RotateCcw className="w-3.5 h-3.5 mr-1.5" />
                    Return
                  </Button>
                  <Button
                    variant="error"
                    className="flex-1"
                    onClick={() => setShowRejectModal(true)}
                  >
                    <XCircle className="w-3.5 h-3.5 mr-1.5" />
                    Reject
                  </Button>
                </div>
              </div>
            </CardBody>
          </Card>
        </div>

        {/* Sidebar */}
        <div className="space-y-6">
          <Card>
            <CardHeader title="Approval History" />
            <CardBody>
              <div className="space-y-4">
                {(wo.approvalChain || []).length === 0 && (
                  <p className="text-sm text-muted-foreground">No approval history yet.</p>
                )}
                {(wo.approvalChain || []).map((hist, index) => (
                  <div key={hist.id ?? index} className="flex gap-3">
                    <div className="flex flex-col items-center">
                      <div
                        className={`w-8 h-8 rounded-full flex items-center justify-center ${
                          hist.action === 'Approved'
                            ? 'bg-success/10'
                            : hist.action === 'Rejected'
                              ? 'bg-error/10'
                              : 'bg-primary/10'
                        }`}
                      >
                        {hist.action === 'Approved' ? (
                          <CheckCircle className="w-4 h-4 text-success" />
                        ) : hist.action === 'Rejected' ? (
                          <XCircle className="w-4 h-4 text-error" />
                        ) : (
                          <User className="w-4 h-4 text-primary" />
                        )}
                      </div>
                      {index < (wo.approvalChain || []).length - 1 && (
                        <div className="w-0.5 h-12 bg-border mt-2" />
                      )}
                    </div>
                    <div className="flex-1">
                      <p className="font-medium text-foreground text-sm">
                        {hist.role || hist.approver}
                      </p>
                      <p className="text-xs text-muted-foreground">{hist.approver}</p>
                      {hist.date && (
                        <p className="text-xs text-muted-foreground mt-1">
                          {hist.action}: {hist.date}
                        </p>
                      )}
                      {hist.comments && (
                        <p className="text-xs text-muted-foreground italic mt-1">
                          "{hist.comments}"
                        </p>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </CardBody>
          </Card>

          <Card>
            <CardHeader title="Submission Details" />
            <CardBody>
              <div className="space-y-3">
                <div>
                  <p className="text-xs text-muted-foreground mb-1">Submitted By</p>
                  <p className="text-sm font-medium text-foreground">{wo.created_by || '-'}</p>
                </div>
                <div>
                  <p className="text-xs text-muted-foreground mb-1">Submission Date</p>
                  <p className="text-sm font-medium text-foreground">
                    {wo.createdAt ? new Date(wo.createdAt).toLocaleString() : '-'}
                  </p>
                </div>
                <div>
                  <p className="text-xs text-muted-foreground mb-1">Approval Status</p>
                  <Badge variant="warning">
                    {(wo.approvalStatus || 'pending').replace(/-/g, ' ')}
                  </Badge>
                </div>
                <div>
                  <p className="text-xs text-muted-foreground mb-1">Project</p>
                  <p className="text-sm font-medium text-foreground">{wo.project || '-'}</p>
                </div>
              </div>
            </CardBody>
          </Card>

          <Card>
            <CardHeader title="Vendor Notification" />
            <CardBody>
              <div className="space-y-2">
                <p className="text-sm text-muted-foreground">
                  Upon final approval, vendor will be notified via:
                </p>
                <div className="flex items-center gap-2 p-2 bg-muted/30 rounded text-sm">
                  <Bell className="w-3 h-3 text-primary" />
                  Vendor Portal (automatic)
                </div>
                <div className="flex items-center gap-2 p-2 bg-muted/30 rounded text-sm">
                  <Bell className="w-3 h-3 text-primary" />
                  {wo.vendor?.email ? `Vendor contact: ${wo.vendor.email}` : 'Vendor email not set'}
                </div>
              </div>
            </CardBody>
          </Card>
        </div>
      </div>

      {/* Approve Modal */}
      {showApproveModal && (
        <div className="fixed inset-0 bg-background/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <Card className="max-w-md w-full">
            <CardHeader
              title="Confirm Approval"
              description="You are about to approve this work order"
            />
            <CardBody>
              <div className="space-y-4">
                <div className="flex items-start gap-3 p-4 bg-success/5 border border-success/20 rounded-lg">
                  <CheckCircle className="w-5 h-5 text-success mt-0.5" />
                  <div>
                    <p className="text-sm font-medium text-foreground mb-1">Approving:</p>
                    <p className="text-sm text-foreground">
                      {wo.workOrderNumber || wo.id} &mdash; {wo.title}
                    </p>
                    <p className="text-sm font-semibold text-success mt-2">
                      Amount: {formatBDT(wo.totalAmount)}
                    </p>
                  </div>
                </div>
                <div className="flex gap-2 justify-end">
                  <Button size="sm" variant="outline" onClick={() => setShowApproveModal(false)}>
                    Cancel
                  </Button>
                  <Button size="sm" variant="success" onClick={handleApprove} disabled={submitting}>
                    <CheckCircle className="w-3.5 h-3.5 mr-1.5" />
                    Confirm Approval
                  </Button>
                </div>
              </div>
            </CardBody>
          </Card>
        </div>
      )}

      {/* Reject Modal */}
      {showRejectModal && (
        <div className="fixed inset-0 bg-background/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <Card className="max-w-md w-full">
            <CardHeader title="Reject Work Order" description="Provide a reason for rejection" />
            <CardBody>
              <div className="space-y-4">
                <div className="flex items-start gap-3 p-4 bg-error/5 border border-error/20 rounded-lg">
                  <AlertCircle className="w-5 h-5 text-error mt-0.5" />
                  <div>
                    <p className="text-sm font-medium text-foreground mb-1">Rejecting:</p>
                    <p className="text-sm text-foreground">
                      {wo.workOrderNumber || wo.id} &mdash; {wo.title}
                    </p>
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">
                    Rejection Reason *
                  </label>
                  <textarea
                    value={rejectionReason}
                    onChange={(e) => setRejectionReason(e.target.value)}
                    placeholder="Provide clear explanation..."
                    rows={4}
                    className="w-full px-3 py-2 border border-input rounded-lg focus:outline-none focus:ring-2 focus:ring-primary resize-none"
                  />
                </div>
                <div className="flex gap-2 justify-end">
                  <Button size="sm" variant="outline" onClick={() => setShowRejectModal(false)}>
                    Cancel
                  </Button>
                  <Button size="sm" variant="error" onClick={handleReject} disabled={submitting}>
                    <XCircle className="w-3.5 h-3.5 mr-1.5" />
                    Confirm Rejection
                  </Button>
                </div>
              </div>
            </CardBody>
          </Card>
        </div>
      )}

      {/* Return Modal */}
      {showReturnModal && (
        <div className="fixed inset-0 bg-background/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <Card className="max-w-md w-full">
            <CardHeader title="Return for Revision" description="Send back for corrections" />
            <CardBody>
              <div className="space-y-4">
                <div className="flex items-start gap-3 p-4 bg-warning/5 border border-warning/20 rounded-lg">
                  <RotateCcw className="w-5 h-5 text-warning mt-0.5" />
                  <div>
                    <p className="text-sm font-medium text-foreground mb-1">Returning:</p>
                    <p className="text-sm text-foreground">
                      {wo.workOrderNumber || wo.id} &mdash; {wo.title}
                    </p>
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">
                    Reason for Return *
                  </label>
                  <textarea
                    value={returnReason}
                    onChange={(e) => setReturnReason(e.target.value)}
                    placeholder="What needs to be corrected..."
                    rows={4}
                    className="w-full px-3 py-2 border border-input rounded-lg focus:outline-none focus:ring-2 focus:ring-primary resize-none"
                  />
                </div>
                <div className="flex gap-2 justify-end">
                  <Button size="sm" variant="outline" onClick={() => setShowReturnModal(false)}>
                    Cancel
                  </Button>
                  <Button size="sm" variant="warning" onClick={handleReturn}>
                    <RotateCcw className="w-3.5 h-3.5 mr-1.5" />
                    Confirm Return
                  </Button>
                </div>
              </div>
            </CardBody>
          </Card>
        </div>
      )}
    </div>
  );
}
