// {
//   "id": "WO-AAB-2026-001",
//   "poNumber": "PO-AAB-2026-001",
//   "awardNumber": "AWD-AAB-2026-001",
//   "csNumber": "CS-2026-001",
//   "rfqNumber": "RFQ-2026-015",
//   "requisitionNumber": "MRF-2026-015",
//   "title": "IT Equipment & Computer Hardware — Dhaka Head Office",
//   "category": "IT Equipment",
//   "budgetCode": "BD-ICT-2026-01",
//   "project": "Digital Transformation & IT Infrastructure",
//   "autoGenerated": true,
//   "preparedBy": "Fatema Khatun",

//   "status": "approved",
//   "approvalStatus": "fully-approved",
//   "approvalLevel": "3/3",
//   "vendorStatus": "accepted",
//   "deliveryStatus": "in-progress",
//   "paymentStatus": "partial",

//   "orderDate": "2026-03-28",
//   "vendorAcceptanceDate": "2026-03-30",
//   "deliveryDeadline": "2026-05-15",
//   "acceptanceDeadline": "2026-04-04",

//   "totalAmount": 3250000,
//   "amountPaid": 975000,
//   "totalItems": 64,
//   "deliveredItems": 20,

//   "notificationSent": true,
//   "notificationChannel": "Portal & Email",

//   "deliveryLocation": "Ledars NGO\nHouse 8, Road 136, Gulshan-1\nDhaka-1212, Bangladesh",
//   "paymentTerms": "30 days after GRN & invoice verification",
//   "warrantyPeriod": "24 months",
//   "tcTemplate": "standard",
//   "notes": "All equipment must be installed and configured on-site. Training for 2 hours per department. VAT 15% and AIT 3.5% will be deducted at source per NBR.",

//   "organization": {
//     "name": "Ledars NGO",
//     "nameBn": "অ্যাকশনএইড বাংলাদেশ",
//     "address": "House 8, Road 136, Gulshan-1, Dhaka-1212, Bangladesh",
//     "phone": "+880-2-8837796",
//     "email": "procurement@actionaid.org.bd",
//     "bin": "001234567-0301",
//     "contactPerson": "Fatema Khatun",
//     "contactRole": "Procurement Officer"
//   },

//   "vendor": {
//     "code": "VEN-BD-001",
//     "name": "TechBD Solutions Ltd",
//     "contactPerson": "Md. Tanvir Ahmed",
//     "email": "sales@techbd.com.bd",
//     "phone": "+880-2-8431234",
//     "address": "House 42, Road 11, Banani, Dhaka-1213, Bangladesh",
//     "tin": "301456789012",
//     "bin": "001234567-0201"
//   },

//   "items": [

//     {
//       "id": "4",
//       "sl": 4,
//       "description": "UPS (1.5 KVA)",
//       "specification": "APC Smart-UPS 1500VA, Online, LCD, 230V, Battery Backup 30 min",
//       "unit": "Pcs",
//       "quantity": 25,
//       "unitPrice": 8800,
//       "total": 220000,
//       "delivered": 0,
//       "deliveryStatus": "pending"
//     },
//     {
//       "id": "5",
//       "sl": 5,
//       "description": "Network Switch (24-Port)",
//       "specification": "Cisco SG350-28, 24x Gigabit, 4x SFP, Managed, PoE+",
//       "unit": "Pcs",
//       "quantity": 4,
//       "unitPrice": 30000,
//       "total": 120000,
//       "delivered": 0,
//       "deliveryStatus": "pending"
//     }
//   ],

//   "termsAndConditions": [
//     {
//       "title": "Delivery Obligation",
//       "text": "The Vendor shall deliver all goods to the specified AAB location on or before the delivery deadline. Partial deliveries are acceptable only with prior written approval from AAB Procurement."
//     },
//     {
//       "title": "Quality Standards",
//       "text": "All items must conform to the specifications in this Work Order and the original quotation submitted by the Vendor. AAB reserves the right to inspect and reject non-conforming items."
//     },
//     {
//       "title": "Installation & Training",
//       "text": "Where applicable, the Vendor shall provide installation, setup, and basic training at no additional cost. Training schedule to be coordinated with AAB IT team."
//     },
//     {
//       "title": "Warranty & Defect Liability",
//       "text": "The Vendor warrants all goods for the warranty period specified above. Defective items must be replaced at Vendor's cost within 7 business days of notification."
//     },
//     {
//       "title": "Payment Process",
//       "text": "Payment will be processed after successful delivery, GRN, and invoice verification. AAB follows a 30-day payment cycle via bank transfer (BEFTN/RTGS)."
//     },
//     {
//       "title": "Tax Compliance (NBR)",
//       "text": "VAT at 15% and AIT at 3.5% will be deducted at source as per NBR regulations. The Vendor must hold a valid TIN and BIN."
//     },
//     {
//       "title": "NGOAB Compliance",
//       "text": "This procurement is subject to NGOAB regulations. All documentation must comply with NGOAB reporting requirements."
//     },
//     {
//       "title": "Confidentiality",
//       "text": "The Vendor shall maintain strict confidentiality of all AAB information received in connection with this Work Order."
//     },
//     {
//       "title": "Force Majeure",
//       "text": "Neither party shall be liable for failure due to force majeure events. Affected party must notify the other within 3 business days with supporting evidence."
//     },
//     {
//       "title": "Dispute Resolution",
//       "text": "Disputes shall be settled through arbitration under Bangladesh Arbitration Act, 2001."
//     },
//     {
//       "title": "Termination",
//       "text": "AAB may terminate this Work Order with 15-day written notice if the Vendor fails to comply with any term or condition."
//     },
//     {
//       "title": "Anti-Corruption",
//       "text": "The Vendor confirms compliance with AAB Anti-Corruption Policy. Any bribe to AAB staff will result in immediate contract termination and blacklisting."
//     }
//   ],

//   "approvalChain": [
//     {
//       "approver": "Fatema Khatun",
//       "role": "Procurement Officer",
//       "action": "Prepared",
//       "status": "approved",
//       "date": "2026-03-28 09:00 AM",
//       "comments": "Auto-generated from approved CS-2026-001. All items verified against CS recommendation.",
//       "members": null
//     },
//     {
//       "approver": "Md. Kamal Hossain",
//       "role": "Procurement/Admin Manager",
//       "action": "Approved",
//       "status": "approved",
//       "date": "2026-03-28 11:30 AM",
//       "comments": "Reviewed and approved. Budget allocation confirmed under BD-ICT-2026-01.",
//       "members": null
//     },
//     {
//       "approver": "Procurement Committee",
//       "role": "Procurement Committee",
//       "action": "Approved",
//       "status": "approved",
//       "date": "2026-03-28 03:00 PM",
//       "comments": "Committee reviewed. Vendor selection consistent with CS recommendation. Approved.",
//       "members": [
//         { "name": "Shahana Begum", "role": "Programme Director", "status": "approved" },
//         { "name": "Md. Rafiqul Islam", "role": "Finance Manager", "status": "approved" },
//         { "name": "Dr. Nafisa Akter", "role": "Health Programme Head", "status": "approved" }
//       ]
//     },
//     {
//       "approver": "Farah Kabir",
//       "role": "Country Director (Final Approver)",
//       "action": "Approved",
//       "status": "approved",
//       "date": "2026-03-28 05:15 PM",
//       "comments": "Final approval granted per Authority Matrix. Proceed with vendor notification.",
//       "members": null
//     }
//   ],

//   "notificationLog": [
//     {
//       "channel": "Vendor Portal",
//       "date": "2026-03-28 05:30 PM",
//       "status": "Delivered",
//       "recipient": "TechBD Solutions Ltd"
//     },
//     {
//       "channel": "Email",
//       "date": "2026-03-28 05:30 PM",
//       "status": "Delivered",
//       "recipient": "sales@techbd.com.bd"
//     },
//     {
//       "channel": "Email",
//       "date": "2026-03-30 10:15 AM",
//       "status": "Delivered",
//       "recipient": "Vendor acceptance confirmation sent to procurement team"
//     }
//   ],

//   "attachments": [

//     {
//       "name": "Vendor_Acceptance_Signed.pdf",
//       "size": "856 KB",
//       "url": "/uploads/vendor-acceptance-signed.pdf",
//       "uploadDate": "2026-03-30"
//     },
//     {
//       "name": "Budget_Allocation_BD-ICT-2026-01.pdf",
//       "size": "420 KB",
//       "url": "/uploads/budget-allocation.pdf",
//       "uploadDate": "2026-03-28"
//     }
//   ]
// }
